### ISSUE TITLE
Ability to run phantomas locally

### ISSUE THREAD

**Issue by shama** [macbre/phantomas#112]
Hi! Thanks for this fantastic library! It would be great if I could install and use phantomas locally. This way other modules could use this library as a dependency and extend it on npm. My use case is I'm writing a grunt plugin for performance metrics.

The other benefit is installing is more idiomatic to node.js where users are only asked to do:

``` shell
npm install
npm test
```

with a `package.json` like:

``` json
{
  "scripts": {
    "test": "phantomas --url http://phantomjs.org"
  },
  "dependencies": {
    "phantomas": "0.8.1"
  }
}
```

I'd be happy to help out implementing this so it runs both globally and locally. Thanks!

**Comment by Libida** [comment]
Hi,

phantomas doesn't work locally for me:
    d:\Buildkit>phantomas --url http://localhost:8001/ --verbose
    15:47:29.987 phantomas v1.10.0:
    C:/Users/maryia_sinkevich/AppData/Roaming/npm/node_modules/phantomas/
    15:47:29.988 Options: {"version":false,"V":false,"help":false,"h":false,"colors":false,
    "disable-js":false,"no-externals":false,"progress":false,"silent":false,
    "spy-eval":false,"verbose":true,"v":true,"scroll":false,"film-strip":false, "analyze-css":false,
    "page-source":false,"reporter":"plain","R":"plain","format":"plain","timeout":15,
    "url":"http://localhost:8001/","user-agent":"phantomas/1.10.0 (PhantomJS/1.9.8; win32 x64)"}
    ...
    15:47:30.044 req: <http://localhost:8001/>
    15:47:30.044 Event send emitted
    15:47:30.045 Event pageOpen emitted
    15:47:30.045 Timeout set to 15 sec
    15:47:30.046 Page loading started
    15:47:30.046 Event loadStarted emitted
    15:47:30.092 Loading progress: 10%
    15:47:30.092 Event progress emitted
    15:47:34.073 Event onResourceReceived emitted
    15:47:34.074 Blocked request by phantomjs: <http://localhost:8001/>
    15:47:34.074 Event abort emitted
    15:47:34.075 recv: "start" stage not registered for <http://localhost:8001/>!
    15:47:34.075 contentLength missing: {"url":"http://localhost:8001/"}
    15:47:34.076 recv: HTTP 200 <http://localhost:8001/> [undefined]
    15:47:34.076 Event recv emitted
    15:47:34.076 Event metric emitted
    15:47:34.077 Event metric emitted
    15:47:34.077 Time to first byte: set to NaN ms for #1 request to <http://localhost:8001/> 
    (HTTP 200)
    15:47:34.077 Time to last byte: set to 4030 ms
    15:47:34.077 Event responseEnd emitted
    15:47:34.078 Block domains: assuming "localhost" to be the main domain
    15:47:34.078 Event metric emitted
    15:47:34.078 Performance timing: responseEnd = 1428421654078
    15:47:34.078 Event milestone emitted
    15:47:34.083 Page loading finished ("fail")
    15:47:34.083 Event loadFailed emitted
    15:47:34.083 Exiting with code #254 (Page loading failed)!
    15:47:34.083 Event exit emitted phantomas: (254) Page loading failed
    15:47:34.097 phantomas scope injected

Could you please help in resolving this issue.

**Comment by macbre** [comment]
What does `curl -sv http://localhost:8001 > /dev/null` shows?

**Comment by Libida** [comment]
Thank you for your response.

    d:\Buildkit>curl -sv http://localhost:8001 > /dev/null
    The system cannot find the path specified.

My mistake, didn't observe that server was stopped.
Now everything is working.
