### ISSUE TITLE
Create a simple HTTP server that will act as phantomas entry point

### ISSUE THREAD

**Issue by macbre** [macbre/phantomas#142]
Features:
- adding a test (`PUT /test`)
- checking the test completion / results (`GET /test/:id`)
- websockets for observing the log

Frameworks:
- nodejs + express
- perl + dancer

Use `phantomas` node.js module - https://github.com/macbre/phantomas/issues/152

**Comment by gmetais** [comment]
Hi,

Just writing here in case it can inspire you or anyone. The new version 1.1 of YellowLabTools introduces an API for launching tests. You might be interested to know you can ask the API to return the Phantomas JSON results.

The API normally returns YLT transformed results, but using it with the `partialResult: phantomas` parameter will remove all the YLT bullshit ;)

Example curl command:
```
curl -L 'http://yellowlab.tools/api/runs' -H 'Content-Type: application/json' --data-binary '{"url":"www.google.fr","waitForResponse":true,"partialResult":"phantomas"}'
```

Not very far from what you where talking about here. No websockets for the logs though :) 
The API documentation is here: https://github.com/gmetais/YellowLabTools/wiki/Public-API

**Comment by macbre** [comment]
Nice, thanks @gmetais !
