### ISSUE TITLE
Show requests that are responsible for timeout

### ISSUE THREAD

**Issue by stefanjudis** [macbre/phantomas#216]
In grunt-phantomas we're dealing with a lot of issues regarding timeouts.

Would be nice to have a log message, when checking the general phantomas executable, which shows what resource is responsible for the timeout.

I'm thinking of something like:

```
22:58:38.258 Timeout of 10 s was reached!
22:58:38.258 Resources ['yoursite.com/...' ] did not load in given time
```

Dependent issues: stefanjudis/grunt-phantomas#21 & stefanjudis/grunt-phantomas#23

**Comment by fizerkhan** [comment]
+1
