### ISSUE TITLE
Jserrors generate by injected Code ?

### ISSUE THREAD

**Issue by jedi4ever** [macbre/phantomas#230]
phantomas nodejs v0.10.7 +0ms
phantomas PhantomJS v1.9.7
phantomas phantomas v0.12.1 

I was testing on a site and only got partial content and jserrors.
The page rendered ok in phantomjs screenshot but failed in phantomas.

It mentioned `Type Errors`and `Parse Errors`. (See below)
When disabling the origConsoleLog line in the sendMsg function on scope.js , it worked.
Not sure what was happening there. But it worked :)

```
function sendMsg(type, data) {
  // @see https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#oncallback
  // Stability: EXPERIMENTAL - see issue #62
  /**
  if (typeof window.callPhantom === 'function') {
    window.callPhantom({type: type, data: data});
  }
  **/
 //PDB
 //origConsoleLog.call(console, 'msg:' + stringify({type: type || false, data: data || false}));
}
```

```
TRACE:
 -> /Users/patrick/dev/pusher-stats/node_modules/phantomas/core/scope.js: 124 (in function "sendMsg")
 -> /Users/patrick/dev/pusher-stats/node_modules/phantomas/core/scope.js: 136 (in function "incrMetric")
 -> phantomjs://webpage.evaluate(): 32
 -> /Users/patrick/dev/pusher-stats/node_modules/phantomas/core/scope.js: 186
 -> http://mysite.be/: 26
17:53:49.261 Event jserror emitted
17:53:49.262 TypeError: Type error
17:53:49.262 Backtrace: sendMsg(): undefined @ 124 / incrMetric(): undefined @ 136 / unknown fn: undefined @ 32 / unknown fn: undefined @ 18
6 / unknown fn: undefined @ 26 / unknown fn: undefined @ 26
```

**Comment by AdriwanKenoby** [comment]
It seems that I have an issue related to this one when I test the url http://www.pacificpeche.com
However this page do not contain any errors...

`jsErrors : 41`

`Offenders for jsErrors (41):
Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 8 / unknown fn: phantomjs://code/scope.js @ 216
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / $(): https://www.pacificpeche.com/js/prototype/prototype.js @ 2056 / initialize(): https://www.pacificpeche.com/js/varien/js.js @ 308 / initialize(): https://www.pacificpeche.com/js/soon/ajaxsearch/ajaxsearch.js @ 13 / klass(): https://www.pacificpeche.com/js/prototype/prototype.js @ 80
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 8 / unknown fn: phantomjs://code/scope.js @ 216
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 96 / unknown fn: phantomjs://code/scope.js @ 216 / ready(): https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / promise(): https://www.avis-verifies.com/js/widget_js/widget3.js @ 2 / ready(): https://www.avis-verifies.com/js/widget_js/widget3.js @ 2 / init(): https://www.avis-verifies.com/js/widget_js/widget3.js @ 2 / n(): https://www.avis-verifies.com/js/widget_js/widget3.js @ 2 / unknown fn: https://www.avis-verifies.com/js/widget_js/widget3.js @ 2 / unknown fn: https://www.avis-verifies.com/js/widget_js/widget3.js @ 2
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 96 / unknown fn: phantomjs://code/scope.js @ 216 / ready(): https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / unknown fn: https://www.pacificpeche.com/ @ 1620
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / emit():  @ 4 / unknown fn:  @ 21
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / unknown fn:  @ 10
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / setMetric(): phantomjs://code/scope.js @ 142 / unknown fn:  @ 62
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / emit():  @ 4 / unknown fn:  @ 10
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / setMetric(): phantomjs://code/scope.js @ 142 / unknown fn:  @ 23
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / $(): https://www.pacificpeche.com/js/prototype/prototype.js @ 2056 / mainNav(): https://www.pacificpeche.com/js/varien/menu.js @ 34 / unknown fn: https://www.pacificpeche.com/js/varien/menu.js @ 131 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 7206 / dispatchEvent():  @ 0 / fireEvent_DOM(): https://www.pacificpeche.com/js/prototype/prototype.js @ 7066 / fire(): https://www.pacificpeche.com/js/prototype/prototype.js @ 7055 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / fireContentLoadedEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 7241
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / Sizzle(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4678 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6236 / $$(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4448 / _getForms(): https://www.pacificpeche.com/js/aw_ajaxcartpro/observers/clickOnButtonInCartPageForm.js @ 60 / run(): https://www.pacificpeche.com/js/aw_ajaxcartpro/observers/clickOnButtonInCartPageForm.js @ 10 / unknown fn: https://www.pacificpeche.com/js/aw_ajaxcartpro/ajaxcartpro.js @ 74 / forEach():  @ 0 / each(): https://www.pacificpeche.com/js/prototype/prototype.js @ 859 / startObservers(): https://www.pacificpeche.com/js/aw_ajaxcartpro/ajaxcartpro.js @ 73 / init(): https://www.pacificpeche.com/js/aw_ajaxcartpro/ajaxcartpro.js @ 53 / unknown fn: https://www.pacificpeche.com/ @ 126 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 7206 / dispatchEvent():  @ 0 / fireEvent_DOM(): https://www.pacificpeche.com/js/prototype/prototype.js @ 7066 / fire(): https://www.pacificpeche.com/js/prototype/prototype.js @ 7055 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / fireContentLoadedEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 7241
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / unknown fn: https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2 / j(): https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2 / fireWith(): https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2 / ready(): https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2 / J(): https://www.pacificpeche.com/js/CapAdresse/jquery.min.js @ 2
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / emit():  @ 4 / unknown fn:  @ 26
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / unknown fn:  @ 54
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 4967 / superMatcher(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6003 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6164 / Sizzle(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4726 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6236 / $$(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4448 / truncateOptions(): https://www.pacificpeche.com/js/varien/js.js @ 608 / unknown fn: https://www.pacificpeche.com/js/varien/js.js @ 623 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 7191
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 4967 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6146 / Sizzle(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4726 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6236 / $$(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4448 / unknown fn: https://www.pacificpeche.com/skin/frontend/default/default/js/mageplace/socialbuttons/facebookconnect.js @ 72 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 7191
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 4967 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6146 / Sizzle(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4726 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6236 / $$(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4448 / unknown fn: https://www.pacificpeche.com/skin/frontend/default/default/js/mageplace/socialbuttons/googleconnect.js @ 29 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 7191
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / selectorTagNameSpy():  @ 34 / unknown fn: phantomjs://code/scope.js @ 216 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 4967 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6146 / Sizzle(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4726 / select(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6236 / $$(): https://www.pacificpeche.com/js/prototype/prototype.js @ 4448 / unknown fn: https://www.pacificpeche.com/skin/frontend/default/default/js/mageplace/socialbuttons/twitterconnect.js @ 29 / unknown fn: https://www.pacificpeche.com/js/prototype/prototype.js @ 7191
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / eventSpy():  @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / observeCustomEvent(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6956 / observe(): https://www.pacificpeche.com/js/prototype/prototype.js @ 6938 / _methodized(): https://www.pacificpeche.com/js/prototype/prototype.js @ 456 / unknown fn: https://www.pacificpeche.com/ @ 136
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / unknown fn:  @ 6 / unknown fn:  @ 9
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn:  @ 86 / walk(): phantomjs://code/scope.js @ 39 / unknown fn:  @ 9 / unknown fn:  @ 101 / unknown fn:  @ 102
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / spyEnabled(): phantomjs://code/scope.js @ 197 / unknown fn:  @ 6 / unknown fn:  @ 65 / unknown fn:  @ 66
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / spyEnabled(): phantomjs://code/scope.js @ 197 / unknown fn:  @ 13 / unknown fn:  @ 56 / unknown fn:  @ 57
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / spyEnabled(): phantomjs://code/scope.js @ 197 / unknown fn:  @ 3 / unknown fn:  @ 59 / unknown fn:  @ 60
 * Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / unknown fn:  @ 14 / unknown fn:  @ 16 / unknown fn:  @ 17`
