### ISSUE TITLE
HTTP request headers

### ISSUE THREAD

**Issue by TBeijen** [macbre/phantomas#273]
It would be nice if it is possible to specify certain headers to be included in the request. Some common use-cases:
- Authorization
- Host

If seen as good feature, some things to consider:
- Combined with user agent or cookie, which will have precedence?
- Syntax of param, possibilities include:
  - JSON string, e.g. --headers="{'Host': 'www.mysite.com', 'foo': 'bar'}"
  - CURL style, e.g. --header "Host: www.mysite.com" --header "foo: bar"

**Comment by dudeche** [comment]
I guess it's not clear to me how setting --proxy would fix this.  For example, I may want to test against a stack where all I have is an IP address.  Nginx/apache/etc would use virtualhosts (ergo, Host: header) to make sure the request was routed correctly.  What am I missing?

**Comment by macbre** [comment]
This would work the same as the following curl:

`curl -X localhost:80 http://testing.domain`

**Comment by dudeche** [comment]
I think you mean a lowercase "x" there.  The uppercase "X" argument definitely wouldn't apply here.  I still don't see how this would correctly set the Host HTTP header.   The original request, I believe, was looking for something like:

curl -H "Host: mycooldomain.com" http://43.23.12.32

Nginx/Apache/Whatever, reads the Host: header to determine how it should route the the configuration for that request.  Anyway, it would be super useful to do this with phantomas.

**Comment by macbre** [comment]
`curl -x localhost:80 http://testing.domain` works fine for me with Apache. True, it does not set the `Host` header explicitly, but Apache uses the correct vhost.
