### ISSUE TITLE
Improve timeouts handling

### ISSUE THREAD

**Issue by devilmike** [macbre/phantomas#380]
I have a few company sites I am running this on and all are fine except for one where the first command line response is "phantomas: (252) Timeout". The difference with this site compared to the others is that it's an api driven site (json, js framework, client-side templates, etc.). Unfortunately I can't post a url but here are the results. Any ideas about what is causing the timeout would be great appreciated.

$ phantomas http://xxxxxx.com
phantomas: (252) Timeout
phantomas v1.5.0 metrics for <http://xxxxxx.com/>:

* requests: 17
* gzipRequests: 6
* postRequests: 1
* httpsRequests: 0
* notFound: 0
* bodySize: 77378
* contentLength: 756774
* httpTrafficCompleted: 1409
* timeToFirstByte: 2549
* timeToLastByte: 2560
* ajaxRequests: 10
* htmlCount: 5
* htmlSize: 20416
* cssCount: 2
* cssSize: 65637
* jsCount: 8
* jsSize: 669377
* jsonCount: 1
* jsonSize: 671
* imageCount: 1
* imageSize: 673
* videoCount: 0
* videoSize: 0
* webfontCount: 0
* webfontSize: 0
* base64Count: 0
* base64Size: 0
* otherCount: 0
* otherSize: 0
* cacheHits: 0
* cacheMisses: 0
* cachePasses: 0
* cachingNotSpecified: 1
* cachingTooShort: 10
* cachingDisabled: 0
* oldCachingHeaders: 10
* consoleMessages: 0
* cookiesSent: 0
* cookiesRecv: 1464
* domainsWithCookies: 1
* documentCookiesLength: 272
* documentCookiesCount: 3
* documentHeight: 1024
* domains: 2
* maxRequestsPerDomain: 10
* medianRequestsPerDomain: 8.5
* commentsSize: 0
* hiddenContentSize: 0
* whiteSpacesSize: 390
* DOMelementsCount: 25
* DOMelementMaxDepth: 5
* nodesWithInlineCSS: 0
* DOMmutationsInserts: 0
* DOMmutationsRemoves: 0
* DOMmutationsAttributes: 0
* DOMqueries: 45
* DOMqueriesById: 7
* DOMqueriesByClassName: 20
* DOMqueriesByTagName: 18
* DOMqueriesByQuerySelectorAll: 0
* DOMinserts: 5
* DOMqueriesDuplicated: 12
* eventsBound: 11
* globalVariables: 15
* globalVariablesFalsy: 0
* headersCount: 240
* headersSentCount: 78
* headersRecvCount: 162
* headersSize: 9492
* headersSentSize: 3357
* headersRecvSize: 6135
* headersBiggerThanContent: 1
* documentWriteCalls: 0
* evalCalls: 5
* jQueryVersion: 1.9.1
* jQueryOnDOMReadyFunctions: 0
* jQuerySizzleCalls: 22
* jsErrors: 5
* localStorageEntries: 0
* redirects: 0
* redirectsTime: 0
* assetsNotGzipped: 10
* assetsWithQueryString: 0
* assetsWithCookies: 1
* smallImages: 1
* multipleRequests: 0
* timeToFirstCss: 431
* timeToFirstJs: 398
* timeToFirstImage: 1013
* domInteractive: 520
* domContentLoaded: 520
* domContentLoadedEnd: 527
* domComplete: 726
* timeBackend: 78
* timeFrontend: 22
* statusCodesTrail: 200
* windowAlerts: 0
* windowConfirms: 0
* windowPrompts: 0
* bodyHTMLSize: 2866
* iframesCount: 0
* imagesWithoutDimensions: 0
* smallestResponse: 215
* biggestResponse: 414235
* fastestResponse: 113
* slowestResponse: 2560
* smallestLatency: 109
* biggestLatency: 2549
* medianResponse: 196
* medianLatency: 162

Offenders for gzipRequests (6):
 * http://xxxxxx.com/ (gzip: 10.46 kB / uncompressed: 10.46 kB)
 * http://xxxxxx.com/api.php/navigation/dynamic (gzip: 0.21 kB / uncompressed: 0.21 kB)
 * http://xxxxxx.com/api.php/merchants/group?group=United%20Top%20Stores%2088x31&max=10&pid=977&sid=9082 (gzip: 3.20 kB / uncompressed: 3.20 kB)
 * http://xxxxxx.com/api.php/categories?global=true (gzip: 5.50 kB / uncompressed: 5.50 kB)
 * http://xxxxxx.com/authorization-provider.php (gzip: 0.66 kB / uncompressed: 0.66 kB)
 * http://xxxxxx.com/api.php/stores-for-you?pid=977&sid=5938&max_fav=3&max_reco=3 (gzip: 0.57 kB / uncompressed: 0.57 kB)

Offenders for postRequests (1):
 * http://xxxxxx.com/authorization-provider.php

Offenders for ajaxRequests (10):
 * http://xxxxxx.com/authorization-provider.php
 * http://xxxxxx.com/api.php/categories?global=true
 * http://xxxxxx.com/api.php/merchants/group?group=United%20Top%20Stores%2088x31&max=10&pid=977&sid=9082
 * http://xxxxxx.com/api.php/stores-for-you?pid=977&sid=5938&max_fav=3&max_reco=3
 * http://xxxxxx.com/api.php/navigation/dynamic
 * http://xxxxxx.com/rwd/views/header.ejs
 * http://xxxxxx.com/rwd/views/nav.ejs
 * http://xxxxxx.com/rwd/views/tos.ejs
 * http://xxxxxx.com/rwd/views/catlist.ejs
 * http://xxxxxx.com/rwd/views/pers.ejs

Offenders for htmlCount (5):
 * http://xxxxxx.com/ (10.46 kB)
 * http://xxxxxx.com/api.php/navigation/dynamic (0.21 kB)
 * http://xxxxxx.com/api.php/merchants/group?group=United%20Top%20Stores%2088x31&max=10&pid=977&sid=9082 (3.20 kB)
 * http://xxxxxx.com/api.php/categories?global=true (5.50 kB)
 * http://xxxxxx.com/api.php/stores-for-you?pid=977&sid=5938&max_fav=3&max_reco=3 (0.57 kB)

Offenders for cssCount (2):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/css/mn/mn_brand_employee_rwd.css (63.49 kB)
 * http://xxxxxx.com/rwd/fonts/fontAwesome/style.css (0.60 kB)

Offenders for jsCount (8):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/parseUri.js (1.22 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/onImageLoad.js (3.83 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/owl.carousel.min.js (23.33 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/mn.js (18.90 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/model.js (20.87 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js (97.37 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js (83.65 kB)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js (404.53 kB)

Offenders for jsonCount (1):
 * http://xxxxxx.com/authorization-provider.php (0.66 kB)

Offenders for imageCount (1):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/global/ajax-loader.gif (0.66 kB)

Offenders for cachingNotSpecified (1):
 * http://xxxxxx.com/rwd/fonts/fontAwesome/style.css

Offenders for cachingTooShort (10):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/parseUri.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/onImageLoad.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/owl.carousel.min.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/mn.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/css/mn/mn_brand_employee_rwd.css cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/model.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js cached for 1800 s
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/global/ajax-loader.gif cached for 86400 s

Offenders for oldCachingHeaders (10):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/parseUri.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/onImageLoad.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/owl.carousel.min.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/mn.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/css/mn/mn_brand_employee_rwd.css - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/model.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js - Expires: Tue, 12 Aug 2014 22:07:13 GMT
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/global/ajax-loader.gif - Expires: Wed, 13 Aug 2014 21:37:14 GMT

Offenders for domainsWithCookies (1):
 * xxxxxx.com: 8 cookie(s)

Offenders for domains (2):
 * a786.g.akamai.net: 10 request(s)
 * xxxxxx.com: 7 request(s)

Offenders for DOMqueriesByClassName (20):
 * .e
 * .e
 * .mn_featStr
 * .mn_dotw
 * .mn_pers
 * .mn_tos
 * .mn_mostPop
 * .mn_promo120x90
 * .mn_catList
 * .mn_catList
 * .mn_tos
 * .mn_tos
 * .mn_promo120x90
 * .mn_mostPop
 * .mn_pers
 * .mn_pers
 * .mn_nav
 * .mn_nav
 * .mn_ajaxSpinner
 * .mn_ajaxSpinner

Offenders for DOMqueriesByTagName (18):
 * *
 * a
 * input
 * tbody
 * link
 * *
 * script
 * script
 * nav
 * body
 * script
 * script
 * *
 * header
 * header
 * body
 * td
 * *

Offenders for DOMinserts (5):
 * "div#sizzle-14078794339920" appended to "html"
 * "DocumentFragment > div.mn_ajaxSpinner" appended to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_pgeColLft > nav.mn_nav.mn_sect.mn_tabSect"
 * "div" appended to "body"
 * "div" appended to "body > div[19]"
 * "div" appended to "body > div[19] > div[0]"

Offenders for DOMqueriesDuplicated (12):
 * tag name "*": 4 queries
 * tag name "script": 4 queries
 * class ".mn_pers": 3 queries
 * class ".mn_tos": 3 queries
 * class ".e": 2 queries
 * class ".mn_mostPop": 2 queries
 * class ".mn_promo120x90": 2 queries
 * class ".mn_catList": 2 queries
 * tag name "body": 2 queries
 * class ".mn_nav": 2 queries
 * class ".mn_ajaxSpinner": 2 queries
 * tag name "header": 2 queries

Offenders for eventsBound (11):
 * "DOMContentLoaded" bound to "#document"
 * "load" bound to "window"
 * "resizeEnd" bound to "window"
 * "resize" bound to "window"
 * "mouseover" bound to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_pgeColLft > aside.mn_catList.mn_sect.mn_tabSect"
 * "mouseout" bound to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_pgeColLft > aside.mn_catList.mn_sect.mn_tabSect"
 * "removed" bound to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_pgeColLft > aside.mn_catList.mn_sect.mn_tabSect"
 * "removed" bound to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_colsWrap > div#mn_pgeColRgt > article.mn_tos.mn_sect.mn_tabSect"
 * "removed" bound to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_colsWrap > div#mn_pgeColRgt > article.mn_pers.mn_sect.mn_tabSect"
 * "removed" bound to "body > div.mn_wrapAll > div.mn_bodyContent > div#mn_pgeColLft > nav.mn_nav.mn_sect.mn_tabSect"
 * "removed" bound to "body > div.mn_wrapAll > header[1]"

Offenders for globalVariables (15):
 * $
 * mnjQuery
 * jQuery
 * mn
 * can
 * Mustache
 * jQuery19103617309012915939
 * FeatstoreModel
 * DealofTheWeekModel
 * NavigationModel
 * StoresForYouModel
 * TopOnlineStoreModel
 * MostPopularOffersModel
 * FeaturedOnlineOffersModel
 * fn

Offenders for headersBiggerThanContent (1):
 * http://xxxxxx.com/api.php/navigation/dynamic (body: 0.21 kB / headers: 0.45 kB)

Offenders for jsErrors (5):
 * TypeError: 'undefined' is not an object (evaluating 'this.template.fn.call') - unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6973 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6952 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2661 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2452 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js @ 207 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 586 / Constructor(): http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 651 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js @ 228 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.mal
lnetworks.com/images/js/mn/pages/control.js @ 2267
 * TypeError: 'undefined' is not an object (evaluating 'this.template.fn.call') - unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6973 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6952 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2661 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2452 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js @ 191 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.a
kamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 5966 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / k(): http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4
 * TypeError: 'undefined' is not an object (evaluating 'this.template.fn.call') - unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6973 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6952 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2661 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2452 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js @ 96 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.ak
amai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 5966 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / k(): http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4
 * TypeError: 'undefined' is not an object (evaluating 'this.template.fn.call') - unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6973 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6952 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2661 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2452 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js @ 55 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.ak
amai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 5966 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / k(): http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4
 * TypeError: 'undefined' is not an object (evaluating 'this.template.fn.call') - unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6973 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 6952 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2661 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 2452 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js @ 172 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.a
kamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js @ 5966 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 2 / k(): http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4 / unknown fn: http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js @ 4

Offenders for assetsNotGzipped (10):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/parseUri.js (JS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/onImageLoad.js (JS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/owl.carousel.min.js (JS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/mn.js (JS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/css/mn/mn_brand_employee_rwd.css (CSS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/model.js (JS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/js_lib/jquery1.9.1.js (JS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/pages/control.js (JS)
 * http://xxxxxx.com/rwd/fonts/fontAwesome/style.css (CSS)
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js (JS)

Offenders for assetsWithCookies (1):
 * http://xxxxxx.com/rwd/fonts/fontAwesome/style.css (CSS)

Offenders for smallImages (1):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/global/ajax-loader.gif (0.66 kB)

Offenders for timeToFirstCss (431):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/css/mn/mn_brand_employee_rwd.css received in 431 ms

Offenders for timeToFirstJs (398):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/parseUri.js received in 398 ms

Offenders for timeToFirstImage (1013):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/global/ajax-loader.gif received in 1013 ms

Offenders for smallestResponse (215):
 * http://xxxxxx.com/api.php/navigation/dynamic (0.21 kB)

Offenders for biggestResponse (414235):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/can.custom.js (404.53 kB)

Offenders for fastestResponse (113):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/parseUri.js (113 ms)

Offenders for slowestResponse (2560):
 * http://xxxxxx.com/ (2560 ms)

Offenders for smallestLatency (109):
 * http://a786.g.akamai.net/f/786/35975/5d/i.xxxxxx.com/images/js/mn/_core/rwd/global/js_plugs/owl.carousel.min.js (109 ms)

Offenders for biggestLatency (2549):
 * http://xxx.com/ (2549 ms)

**Comment by Heidistein** [comment]
I appear to have the same issue on here:
https://www.transavia.com/de-DE/startseite

**Comment by tufandevrim** [comment]
I have the same issue. I especially get this frequently when I run multiple tests with --run option. 
Ideally phantomas should not exit with "phantomas: (252) Timeout" and should return available metrics with appropriate status code like: partially complete for run array item in the runs object. stats should not include the the failed or partially completed tests

**Comment by macbre** [comment]
I think the best option here would be to simply skip the failed tests (when in multiple runs mode) and only include the successful ones in the stats. @tufandevrim, sounds fine?

**Comment by tufandevrim** [comment]
yes it would be perfect.
