### ISSUE TITLE
include-dirs when using phantomas as node-module

### ISSUE THREAD

**Issue by mmatzanke** [macbre/phantomas#384]
Hey,

I got a problem to include external(my) modules with "include-dirs" option when I using phantomas as node module dependency. It references within the `listModulesInDir` function to the path of phantomas (in node_modules) itself. 

example:

``` javascript
var phantomas = require("phantomas");
      phantomas('url', {'include-dirs': './app/modules/'}, function(err, resultJSON, result){/*do stuff*/});
```

I'm not sure if I'm right but I think its because of the spawning of processes and permissions to the fs.

Can I handle this in another way ?

Thanks in advance!
Martin

**Comment by ts-web** [comment]
I just figured out the same problem.

All the modules in the include-dir must be in a folder of the same name as their JS file.

For me, I ran phantomas with the option `--include-dirs=server/phantomas-modules`, and my module "links" had to be placed at `server/phantomas-modules/links/links.js`.

**Comment by macbre** [comment]
@ts-web, @mmatzanke - I've improved the docs in f75ec9c.

Hope it's way more clear now.
