### ISSUE TITLE
Scope problem with the spied version of eval() - introduce --spy-eval option

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#467]
Hi there! Sorry for disturbing during the holidays :)

I have a bug with Phantomas counting a jsError on this page:
```
phantomas --url=http://www.francetvinfo.fr --timeout=30
```
The error is `ReferenceError: Can't find variable: oEl - unknown fn:  @ 1`.

Here is the portion of code responsible for the problem:
```js
function xtP(oEl, inTYPE) {
    if (typeof (oEl.offsetParent) != un) {
        var sType = 'oEl.offset' + inTYPE;
        for (var iVal = 0; oEl; oEl = oEl.offsetParent) {
            iVal += eval(sType);
        }
        return iVal;
    }
    return -1;
}
```
oEl is correctly defined inside the function, but not inside eval.

When the javaScriptBottleneck module is disabled, the error disappears. The reason was hard to determine, but i finally found. Eval is made to run in the scope of the calling function, but phantomas' spy function is changing the scope.

Simplified example:
```js
// Code example that works because it's using the original eval function
function workingScript() {
    var foo = 999;
    return eval('foo');
};

console.log(workingScript());
// 999


// Simulating the spy function for eval
function spyedEval(code) {
    var origEval = eval;
    return origEval.apply(this, [code]);
};

// Code example using the spyed function
function buggingScript() {
    var foo = 999;
    return spyedEval('foo');
};

console.log(buggingScript());
// ReferenceError: foo is not defined
```

Here is what MDN says about eval:
> You cannot indirectly use the eval function by invoking it via a name other than eval(); if you do, a runtime error might occur. For example, you should not use the following code:

> ```var x = 2;
var y = 4;
var myEval = eval;
myEval("x + y");```

([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval))

So i don't have any solution for the moment, and it looks like it's going to be difficult to fix this... Any idea?

**Comment by macbre** [comment]
@gmetais, thanks for the bug report. ``eval`` is simply broken by design :)

What about adding ``--enable-eval-spy`` flag to enable spying of ``eval`` calls on demand to avoid JS errors that can skew other metrics?

**Comment by gmetais** [comment]
That would be perfect!
