### ISSUE TITLE
cachingNotSpecified reports files with the Expires: header specified

### ISSUE THREAD

**Issue by unintelligible** [macbre/phantomas#468]
The documentation seems to indicate that the 'cachingNotSpecified' metric should only report requests where the Cache-Control or Expires headers aren't specified:

> cachingNotSpecified: responses with no caching header sent (either Cache-Control or Expires)

I think this is the correct behaviour, as most browsers understand both headers and use of the Expires header is already reported in 'oldCachingHeaders'.

However, https://github.com/macbre/phantomas/blob/devel/modules/caching/caching.js seems to discard the Expires header, and therefore includes response with the Expires header set in the 'cachingNotSpecified' metric:

    case 'expires':
    case 'pragma':
    // and Varnish specific headers
    case 'x-pass-expires':
    case 'x-pass-cache-control':
        phantomas.incrMetric('oldCachingHeaders'); // @desc number of responses with old, HTTP 1.0 caching headers (Expires and Pragma)
	phantomas.addOffender('oldCachingHeaders', url + ' - ' + headerName + ': ' + value);
	break; // <-- ** no return value here **

**Comment by unintelligible** [comment]
I think the fix may be as simple as:

    case 'expires':
    case 'pragma':
    // and Varnish specific headers
    case 'x-pass-expires':
    case 'x-pass-cache-control':
        phantomas.incrMetric('oldCachingHeaders'); // @desc number of responses with old, HTTP 1.0 caching headers (Expires and Pragma)
        phantomas.addOffender('oldCachingHeaders', url + ' - ' + headerName + ': ' + value);
        --------------- start
        var now = new Date(),
            headerDate = Date.parse(value);
        if (headerDate) ttl = (headerDate - now) / 1000;   
        --------------- end
        break;

Happy to submit a properly formatted pull request if you are happy with this solution.

**Comment by macbre** [comment]
Please go ahead with the pull request. Thanks for the bug report, @unintelligible :)
