### ISSUE TITLE
Filmstrip and Screenshopt doesn't render webfonts (gruntjs)

### ISSUE THREAD

**Issue by mpy-pixum** [macbre/phantomas#490]
Hallo, i tried to measure my site with phantomas and the grunt plugin but the webfont doesn't render on the screenshots or the filmstrip plugin (.woff, .eot, .svg - google webfont loader)

Any suggestions? I already tried to use slimerjs (gecko) but everything seems pretty the same.

**Comment by macbre** [comment]
@mpy-pixum, this seems to be an issue on PhantomJS side - https://github.com/ariya/phantomjs/issues/10592

The good news is that this one should be fixed in PhantomJS 2 (which we're planning to switch to in the near future).
