### ISSUE TITLE
Cannot bind document.getElementById : TypeEror  'undefined' is not a function

### ISSUE THREAD

**Issue by Lucas-C** [macbre/phantomas#491]
Hello,

I'm using the following helper "shorthand" functions:

    module.exports = {
        byId: document.getElementById.bind(document),
        create: document.createElement.bind(document),
        select: document.querySelector.bind(document),
        selectAll: document.querySelectorAll.bind(document),
       ...
    }

But because of this `phantomas` dies miserably with the following error:

    TypeError: 'undefined' is not a function (evaluating 'document.getElementById.bind(document)')

From what I could understand, `phantomas` [sets "spies" on DOM methods](https://github.com/macbre/phantomas/blob/4490fc8822947ce60813483d9eaf1f19e0e0afeb/modules/domQueries/domQueries.js#L28).

Hence is there a workaround to this issue ?

I guess I could instead define a function that would invoke `document.getElementById.apply(document, arguments)`, but will that even work ?
Shouldn't the "spies" have the basic `Function.prototype` methods ?

**Comment by macbre** [comment]
They definitely should. I'll investigate the issue.

**Comment by macbre** [comment]
PhantomJS (v 1.x) does not support `Function.prototype.bind` - https://github.com/ariya/phantomjs/issues/10522

You can consider using a polyfill to fix this issue - https://github.com/macbre/phantomas/blob/devel/core/phantomas.js#L14-21

Closing as won't fix - we're waiting for the release of PhantomJS 2.x that will have a better support for ECMAScript 5 features.

**Comment by Lucas-C** [comment]
Ok thanks
