### ISSUE TITLE
Phantomas library doesnt seem to honor "runs" option

### ISSUE THREAD

**Issue by pranavparikh** [macbre/phantomas#492]
Modifying the example provided at https://github.com/macbre/phantomas/wiki/npm-module to set no. of runs, I see that the time it takes for 1 run is almost same as the time for 5 runs.

This leads me to think that it's running the tests only once. How do I make sure or check that phantomas is running the test no. of times passed in "run" ?  I'm doing something wrong here or expecting something else ?

#!/usr/bin/env node
var phantomas = require('phantomas');

console.log(phantomas); // { [Function: phantomas] path: '...', version: '1.0.0' }

phantomas('http://example.com', {"analyze-css": true, "runs": 5}, function(err, json, results) {
        console.log([
                'phantomas results',
                err, // null or exit code from phantomas process
                json, // parsed JSON with raw results
                results // results object with metrics values, offenders, asserts data
        ]);
});

**Comment by macbre** [comment]
@pranavparikh, that's actually an issue of documentation being misleading. phantomas npm module does not "directly" support multiple runs. You have to run it in a loop - https://github.com/macbre/phantomas/blob/devel/bin/phantomas.js#L134-204

Sorry for the confusion, I'll correct the docs.

**Comment by pranavparikh** [comment]
@macbre 
Thanks for taking a look.

**Comment by macbre** [comment]
Docs updated - https://github.com/macbre/phantomas/wiki/npm-module#limitations
