### ISSUE TITLE
Count images that could be lazyloaded

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#494]
An idea for a new metric: count the number of `<img>` that could be lazy loaded on scroll.

Most of the time, an image should be lazyloaded in these two cases:
- it is below the fold (absolute top position > viewport's height)
- it is hidden (display:none or visibility:hidden, or one of its parents)

and 
- it's not also displayed above the fold

There might be some special cases - such as horizontal scrolling - that would not be handled, but I find it interesting anyway.

**Comment by macbre** [comment]
Makes sense. Please file a separate issue for the default viewport.
