### ISSUE TITLE
Film-strip - colons (:) are not allowed in file name on windows.

### ISSUE THREAD

**Issue by vinvol** [macbre/phantomas#498]
Hi,

after a few failures trying to capture the film-strip, I realized the file name contained a date formatted with toJSON().

filmStrip.js:39
```javascript
		startFormatted = (new Date()).toJSON().substr(0, 19), // 2014-05-18T13:08:13
```

Colons are not accepted in file names on windows, so the render will fail.

**Comment by macbre** [comment]
Thanks!
