### ISSUE TITLE
Transfer proxy config to analyze-css

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#500]
When a proxy is set in Phantomas, analyze-css doesn't use it. This sometime prevents css files from being correctly analyzed.

It would be great!

* [x] - pass proxy settings
* [x] - pass HTTP authentication

**Comment by gmetais** [comment]
Same thing for Basic HTTP authentication.

**Comment by macbre** [comment]
[v1.17.0](https://github.com/macbre/phantomas/releases/tag/v1.17.0) has been released :)
