### ISSUE TITLE
Filmstrip viewport on HDPi screens?

### ISSUE THREAD

**Issue by zachleat** [macbre/phantomas#501]
On my Retina macbook, using `phantomas http://www.filamentgroup.com/ --film-strip --viewport=320x480 --engine=webkit` the final screenshot outputs at the correct dimension (320), but the viewport shows 640px of content in that space.

For example, how filamentgroup.com looks (at a 320px viewport in Chrome):

![image](https://cloud.githubusercontent.com/assets/39355/6338571/74a3c812-bb75-11e4-8a59-59de0cd26543.png)

But the `--viewport=320x480` film strip looks like this in phantomas:

![image](https://cloud.githubusercontent.com/assets/39355/6338591/94b47d9a-bb75-11e4-9e4d-569a77335ee2.png)

This seems to match what a 640px viewport looks like in Chrome.

**Comment by macbre** [comment]
I think we can blame [this line that set the zoom level to 50% for taking screenshots](https://github.com/macbre/phantomas/blob/devel/extensions/filmStrip/filmStrip.js#L28). So it's actually phantomas feature, not a HDPi-related bug :)

Feel free to file a feature request to customize the zoom level.

**Comment by zachleat** [comment]
Oh, that’s good news—thanks!

In addition to the feature request, could you be persuaded to changing the default too? It was certainly unexpected, at least to me.

**Comment by macbre** [comment]
Sure, @zachleat :)

**Comment by rosswilson** [comment]
I've stumbled across this issue today and have submitted a PR (#709) to make the zoom factor an optional parameter.

**Comment by macbre** [comment]
Thanks, @rosswilson !
