### ISSUE TITLE
Count the number of window.addEventListener('scroll', ...)

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#508]
If too much JS is executed on the `scroll` event, the FPS can become really slow on page scroll.

All of the JS code executed on scroll goes through this function: 
```window.addEventListener('scroll', callback)```

It would be difficult to detect the complexity and execution time of the callback functions, but counting the number of bindings is a good start!

**Comment by macbre** [comment]
Let's call it `scrollEventsBound`
