### ISSUE TITLE
Stop phantomas at onLoad event

### ISSUE THREAD

**Issue by Verkurkie** [macbre/phantomas#513]
Suggestion for new metrics: count & bytes of <html, css, js, json, image, webfont, video, base64 and other> before the onLoad event.

(Note: these are the same metrics that are currently in the 'Asset types' group - but the count is for the entire page)

Alternative: a command-line parameter that will cause phantomAS to stop running at the unload event! This is similar to Marcel Duran's webpagetest-api wrapper. It has a parameter '--onload' ...

Many objects that are loading before onload could be 'render-blocking' and should be lazy loaded (especially CSS and JS). For folks that are focused on lazy loading of content, this can be very useful. Also, many sites have 3rd party content that is already loading after onload and as such, the current total page counts are not specific enough.

**Comment by macbre** [comment]
Stopping at the onload event (via `--stop-at-onload` option) makes more sense here (instead of duplicating the metrics).
