### ISSUE TITLE
Is it being throttled?

### ISSUE THREAD

**Issue by callumacrae** [macbre/phantomas#538]
I've been generating [this](http://lostmyname.github.io/load-time-graph/) manually for a while now, and I'm looking for ways I can automate it.

The unthrottled load time of the site I'm testing is 2.47s, but "domComplete" is around 7000ms when ran through phantomas. Is it being throttled, or is PhantomJS just really slow?

**Comment by macbre** [comment]
PhantomJS does not throttle the HTTP traffic.

@callumacrae, page URL please.

**Comment by callumacrae** [comment]
https://www.lostmy.name/

**Comment by macbre** [comment]
I get similar times from phantomas and chrome:

```
$ phantomas "https://www.lostmy.name/" --verbose --webkit2

phantomas v1.12.0 metrics for <https://www.lostmy.name/>:

* requests: 130
* gzipRequests: 39
* postRequests: 6
* httpsRequests: 130
* notFound: 0
* bodySize: 1495055 bytes
* contentLength: 1766996 bytes
* httpTrafficCompleted: 7830 ms
* timeToFirstByte: 550 ms
* timeToLastByte: 590 ms
* domInteractive: 843 ms
* domContentLoaded: 839 ms
* domContentLoadedEnd: 876 ms
* domComplete: 4641 ms
* timeBackend: 11 %
* timeFrontend: 89 %
```

Please note that some of phantomas modules do perform heavy operations (like querying the DOM), so you can get different results.

You can run phantomas with `--modules=windowPerformance` CLI option to skip all these heavy operations and just get the performance data.
