### ISSUE TITLE
Metric: Resources Responsible for Timeout

### ISSUE THREAD

**Issue by peterstory** [macbre/phantomas#539]
I'm working on a script that uses Phantomas to monitor a web page's performance over the course of the day. Looking over my data, I noticed a number of timeouts, and I'd like to find out which resources are responsible for the timeouts. I noticed that in response to issue #216, verbose mode logs something like the following:

    13:12:24.267 Timeout of 2 sec was reached!
    13:12:24.267 Event timeout emitted
    13:12:24.267 Timeout: gave up waiting for 37 HTTP response(s): <URLS here>

However, I'd prefer not to have to grep for this message: it would be much more convenient if the resources responsible for the timeout were listed in a metric. Would it be possible to implement this feature? (Also, this project is fantastic, keep up the good work!)

**Comment by macbre** [comment]
I'd rather improve the error message that is returned to both console (when run in cli mode) and node.js client. I'll give it a thought.

And thanks :)

**Comment by macbre** [comment]
`requestsWithTimeout` "fake" metric will be emitted.

```
$ phantomas "http://foo.net/" --timeout 1 --verbose 2>&1 | grep -i timeout

phantomas: (252) Timeout
--
* requestsWithTimeout: 8
--
Offenders for requestsWithTimeout (8):
 * http://xxx.log.optimizely.com/event?xxx
 * http://img4.xxx.nocookie.net/...
...
```
