### ISSUE TITLE
When running phantomas API, i am getting "TypeError: Bad Argument"

### ISSUE THREAD

**Issue by fizerkhan** [macbre/phantomas#545]
I installed phantomas(`npm install phantomas --save`) in my node project,  I am running following  code to get performance details

    phantomas('http://www.google.com', {"analyze-css": true}, function(err, json, results) {
         console.log([
             'phantomas results',
             err, // null or exit code from phantomas process
             json, // parsed JSON with raw results
             results // results object with metrics values, offenders, asserts data
        ]);
    });

But i got an error

    TypeError: Bad argument
        at TypeError (native)
        at ChildProcess.spawn (child_process.js:1129:26)
        at exports.spawn (child_process.js:988:9)
        at engines.run (/Users/mine/myproject/node_modules/phantomas/lib/engines.js:109:10)
        at phantomas (/Users/mine/myproject/node_modules/phantomas/lib/index.js:64:16)
        at repl:1:1
        at REPLServer.defaultEval (repl.js:132:27)
        at bound (domain.js:254:14)
        at REPLServer.runBound [as eval] (domain.js:267:12)
        at REPLServer.<anonymous> (repl.js:279:12)

> I did not install `libfontconfig`. Because doc only provides step for Ubuntu.
> Node version: v0.12.0

**Comment by macbre** [comment]
@fizerkhan, can you try to reproduce this issue on `devel` branch? Which version of node.js do you use?

**Comment by fizerkhan** [comment]
> Node version: v0.12.0.

I will try with `devel` branch.

**Comment by fizerkhan** [comment]
@macbre I tried with `devel` branch. The same error occurs even in `devel` branch.

> Node version: v0.12.0.
> Mac OSX: 10.8

**Comment by macbre** [comment]
@fizerkhan, thanks! I'll take a look at this one.

**Comment by fizerkhan** [comment]
i tried to put debug with `console.log(engine.path, engineArgs);` at the line `engines.run (/Users/mine/myproject/node_modules/phantomas/lib/engines.js:109:10)`

It prints following line

```
null [ '--debug=false',
  '/Users/mine/myproject/node_modules/phantomas/scripts/phantomas.js',
  '{"analyze-css":true,"url":"http://www.google.com","user-agent":"phantomas/1.11.0 (PhantomJS/1.9.8; darwin x64)"}' ]
```

It prints `null` in `engine.path`. But it should be valid path. 

Moreover `engineArgs` has the path of `/Users/mine/myproject/node_modules/phantomas/scripts/phantomas.js`. But this path is wrong.
It should be `/Users/mine/myproject/node_modules/phantomas/bin/phantomas.js`

**Comment by macbre** [comment]
Thanks for debugging! Adding a test script to make it run on Travis for both node.js v0.10 and 0.12.

**Comment by macbre** [comment]
@fizerkhan, empty `engine.path` means that something went wrong with the installation of `phantomjs` npm module. Can you remove `node_modules` directory and re-run `npm install`?

**Comment by fizerkhan** [comment]
@macbre I did this steps more than 5 times. But no luck :-1:

**Comment by macbre** [comment]
Does the CLI tool (`bin/phantomas.js`) work for you?

**Comment by macbre** [comment]
@fizerkhan, is the path in `node_modules/phantomjs/lib/location.js` set to something like:

```js
module.exports.location = "phantom/bin/phantomjs"
```

If not, then it seems to be a problem with `phantomjs` npm package, not the phatomas itself.

**Comment by macbre** [comment]
phantomas prints out the list available engines when in debug mode. It gives me the following:

```
macbre@debian:~/github/phantomas$ DEBUG=phantomas:engines ./examples/promise.js 
phantomas v1.11.0 loaded from /home/macbre/github/phantomas
  phantomas:engines Engine "webkit": PhantomJS v1.9.8 installed in /home/macbre/github/phantomas/node_modules/phantomjs/lib/phantom/bin/phantomjs +0ms
  phantomas:engines Engine "webkit2": PhantomJS v2.0.0 installed in /home/macbre/github/phantomas/node_modules/phantomjs2/lib/phantom/bin/phantomjs +6ms
  phantomas:engines Engine "gecko": SlimerJS v0.9.5 installed in /home/macbre/github/phantomas/node_modules/slimerjs/lib/slimer/slimerjs +6ms
  phantomas:engines Running /home/macbre/github/phantomas/scripts/phantomas.js (using PhantomJS) +1ms
  phantomas:engines Passing phantomas options: {"analyze-css":true,"assert-requests":1,"url":"http://google.is","user-agent":"phantomas/1.11.0 (PhantomJS/1.9.8; linux x64)"} +0ms
  phantomas:engines Passing engine options: ["--debug=false"] +0ms
Running phantomas: pid 4438
```

**Comment by fizerkhan** [comment]
@macbre Thanks for the quick update. I got following

```
phantomas v1.11.0 loaded from /Users/mine/myproject/node_modules/phantomas
  phantomas:engines Engine "webkit": PhantomJS v1.9.8 installed in null +0ms
  phantomas:engines Engine "gecko": SlimerJS v0.9.6 installed in /Users/mine/myproject/node_modules/phantomas/node_modules/slimerjs/lib/slimer/slimerjs +10ms
  phantomas:engines Running /Users/mine/myproject/node_modules/phantomas/scripts/phantomas.js (using PhantomJS) +2ms
  phantomas:engines Passing phantomas options: {"analyze-css":true,"assert-requests":1,"url":"http://google.is","user-agent":"phantomas/1.11.0 (PhantomJS/1.9.8; darwin x64)"} +0ms
  phantomas:engines Passing engine options: ["--debug=false"] +0ms
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
```

It says `PhantomJS v1.9.8 installed in null +0ms`. Why it returns `null` instead of path.
I also have phantomjs under `node_modules/phantomas/node_modules/phantomjs`.

**Comment by macbre** [comment]
No idea why it does not work. 

Try [git cloning](https://github.com/Medium/phantomjs) `phantomjs` npm module and run `npm install` + `npm test`.

**Comment by macbre** [comment]
@fizerkhan - please try with [the latest version of phantomas](https://github.com/macbre/phantomas/releases/tag/v1.12.0)
