### ISSUE TITLE
Provide a proper Error in Node API

### ISSUE THREAD

**Issue by fizerkhan** [macbre/phantomas#548]
I tried following code

```javascript
var phantomasOption = {
    debug: true
 };
require('phantomas')('http://www.walmart.com', phantomasOption, function(err, json, results) {
    console.log('Error in callback', typeof err, err);
    console.log('JSON ', json && json.metrics);
});
```

I found few issues:

1. It returns both error and result. The error is `252` which is number. As node convention, i expect `Error`.

2. I am getting this error for most of the sites. However i could not find why it is happening even with debug flag. Interestingly i also got the result.

**Comment by macbre** [comment]
Error code 252 means "page load timeout" (`EXIT_TIMED_OUT`). You do get the results as the page loaded partially.

Good point on the `err` argument type.

**Comment by fizerkhan** [comment]
@macbre  Thanks. Can you also print debug messages(only when debug flag is set) about which resources causes the timeout?

**Comment by macbre** [comment]
The list of resources that caused the timeout will be handled by #539

**Comment by fizerkhan** [comment]
@macbre Thanks. I think, this feature(debug timeout messages) is worth to implement.
