### ISSUE TITLE
JS redirection generates a 254 error

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#550]
Hi @macbre!

Not sure how this problem could be solved by phantomas.
When a page faces a JavaScript redirection, phantomas fails with the error code 254.

Example on this website: ```phantomas http://danielwong.tk --verbose```

The page starts to load, the assets too, than:
```
10:01:59.840 req: <http://danielwong.tk/tablet/index.html>
10:01:59.840 Event send emitted
10:01:59.841 Page loading finished ("fail")
10:01:59.841 Event loadFailed emitted
10:01:59.842 Exiting with code #254 (Page loading failed)!
```

It would be very cool if phantomas could throw a different error code when this case occurs.

**Comment by fizerkhan** [comment]
+1

I am keep getting this error for more number of pages. It will be great if you make it as high priority bug.

**Comment by macbre** [comment]
@fizerkhan: examples please

**Comment by macbre** [comment]
@gmetais - I've added a test case for JS redirections in #557 and after a small fix (injecting phantomas scope after JS redirect) the redirects itself work and cause no problems.

In this case I'm blaming the following (`Got a response with no status set`):

```
09:36:01.801 req: <http://danielwong.tk/tablet/index.html>
09:36:01.802 Event send emitted
09:36:01.802 Page loading finished ("fail")
09:36:01.802 Event loadFailed emitted
09:36:01.803 Exiting with code #254 (Page loading failed)!
09:36:01.803 Event exit emitted
phantomas: (254) Page loading failed
09:36:01.811 onInit: was already triggered for <http://danielwong.tk/>
09:36:01.812 Event onResourceReceived emitted
09:36:01.812 Got a response with no status set: <http://danielwong.tk/tablet/index.html> ({"contentType":null,"headers":[],"id":9,"redirectURL":null,"stage":"end","status":null,"statusText":null,"time":"2015-09-26T09:36:01.811Z","url":"http://danielwong.tk/tablet/index.html"})
09:36:01.812 Event abort emitted
09:36:01.812 recv: "start" stage not registered for <http://danielwong.tk/tablet/index.html>!
09:36:01.812 contentLength missing: {"url":"http://danielwong.tk/tablet/index.html"}
09:36:01.813 recv: HTTP 200 <http://danielwong.tk/tablet/index.html> [undefined]
```

**Comment by fizerkhan** [comment]
I am getting 254 errors for following sites:

* https://freshvine.co
* http://www.holidayiq.com 

PS: Recently we built a free tool http://www.ismysitefastenough.com/ in which we are monitoring more than 1000 sites. Around 25-30%(nearly 250) of the site are getting 254 errors even though URLs are valid.

**Comment by macbre** [comment]
@fizerkhan, did you try running phantomas using PhantomJS 2.0 (`--engine=webkit2`)?

phantomas runs fine for me for both of these sites when using the latest PhantomJS.

**Comment by fizerkhan** [comment]
@macbre  

- In our production, we have the version `phantomas 1.11.0`. If i update to latest version `phantomas 1.12.0`, will it update to PhantomJS 2.0?
- We are using node API, where should i use this option?

     phantomas('http://example.com', {"engine":"webkit2"}

**Comment by macbre** [comment]
1. It will fetch the statically compiled PhantomJS 2.0 binary (at least try to do so for Debian / Ubuntu / MacOS), but will not use it as a default engine.

2. Correct. Or you can set environmental variable - https://github.com/macbre/phantomas#engines

**Comment by fizerkhan** [comment]
@macbre Thanks. Then i will update package version and `engine` option and check whether it will work or not.

**Comment by fizerkhan** [comment]
@macbre Thanks. Now Most of the sites is working. but few sites are getting 255 error

* https://www.wahanda.com/

**Comment by macbre** [comment]
@fizerkhan, please report a separate issue for 255 errors.

**Comment by fizerkhan** [comment]
@macbre Sorry. I thought so. I will do it.

**Comment by gmetais** [comment]
Hi,

I'm testing the fix with phantomas 1.13 and the issue is still there, at least for the following url:

```
$ phantomas http://danielwong.tk/ --verbose --webkit2

19:51:14.302 Event onResourceRequested emitted
19:51:14.302 Event beforeSend emitted
19:51:14.302 req: <http://danielwong.tk/tablet/index.html>
19:51:14.303 Event send emitted
19:51:14.304 Page loading finished ("fail")
19:51:14.304 Event loadFailed emitted
19:51:14.304 Exiting with code #254 (Page loading failed)!
19:51:14.304 Event exit emitted
phantomas: (254) Page loading failed
19:51:14.312 onInit: was already triggered for <http://danielwong.tk/>
19:51:14.313 Event onResourceReceived emitted
19:51:14.313 Got a response with no status set: <http://danielwong.tk/tablet/index.html> ({"contentType":null,"headers":[],"id":9,"redirectURL":null,"stage":"end","status":null,"statusText":null,"time":"2015-10-28T19:51:14.313Z","url":"http://danielwong.tk/tablet/index.html"})
19:51:14.313 Event abort emitted
19:51:14.313 recv: "start" stage not registered for <http://danielwong.tk/tablet/index.html>!
19:51:14.314 contentLength missing: {"url":"http://danielwong.tk/tablet/index.html"}
19:51:14.314 recv: HTTP 200 <http://danielwong.tk/tablet/index.html> [undefined]
19:51:14.314 Event recv emitted
19:51:14.315 phantomas scope injected
19:51:14.316 onInit: page object initialized
19:51:14.316 Event init emitted
```

**Comment by macbre** [comment]
Interestingly, the URL above works when run using SlimerJS (`--gecko`)

**Comment by coryshaw** [comment]
For what it's worth, I'm still getting lots of 254 errors using the latest version of Phantomas (v 1.17.0). 

Here's some example URLs:
https://www.thenest.com/
http://iyeker.com/
