### ISSUE TITLE
Getting 255 (PhantomJS 2.0.0 crashes) for some sites

### ISSUE THREAD

**Issue by fizerkhan** [macbre/phantomas#558]
I am getting 255 for some of the sites

* http://www.wahanda.com
* http://www.geeksroom.com
* http://www.getbutik.com
* http://www.autozone.com

**Comment by macbre** [comment]
Thanks for reporting

**Comment by fizerkhan** [comment]
@macbre Yes, I am using `--engine=webkit2`

**Comment by macbre** [comment]
All of the above URLs end up with a PhantomJS crash.

```
Debug: PhantomJS has crashed. Please read the crash reporting guide at
<http://phantomjs.org/crash-reporting.html> and file a bug report at
<https://github.com/ariya/phantomjs/issues/new>.
Please attach the crash dump file:
  /tmp/1aeb53c4-1522-d3e4-1a5a3729-02732434.dmp
phantomas: (255) Engine crashed unexpectedly
```

Are you experiencing the same?

And they do work for me using both `--webkit`` (PhantomJS 1.9.x) and `--gecko` (SlimerJS)

**Comment by gmetais** [comment]
Same problem on http://rocssti.net/
Fails on webkit2, works on webkit.

**Comment by macbre** [comment]
Ok, let's try to switch to PhantomJS 2.0.1 - https://github.com/ariya/phantomjs/issues/12902

**Comment by macbre** [comment]
http://rocssti.net/ does work with PhantomJS 2.0.1, I'm going to update https://github.com/macbre/phantomjs2-npm to fetch static builds from Vitallium

**Comment by macbre** [comment]
@fizerkhan / @gmetais - can guys verify that the update of PhantomJS works for you? Thanks :)

**Comment by gmetais** [comment]
It works for me on Linux! Websites that were having this 255 error now work correctly!

Be careful, npm install now fails on Mac OSX, with a 404 error on this file: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.1-macosx.zip
I could not find how to fetch static builds from Vitallium.
