### ISSUE TITLE
phantomas shouldn't modify the `options` parameter

### ISSUE THREAD

**Issue by tillsc** [macbre/phantomas#563]
I struggled a while with this:

    https://github.com/macbre/phantomas/blob/devel/lib/index.js#L53

I ran multiple tests against different URIs. But it was always the first URIs which was actually used.

Consider this code:

~~~javascript
var options = {timeout: 10};

phantomas('https://www.google.de/', options, ...); // Will work as expected
phantomas('https://www.yahoo.com/', options, ...); // Will run against google again
~~~

This could be avoided if the `url` parameter would have precedence over `options.url`. Another option would be not to modify the `options` object itself and just to clone it.

**Comment by macbre** [comment]
Good catch!
