### ISSUE TITLE
can't install phantomas in Linux 2.6.32_1-15-0-0  node v0.12.2 npm  v2.14.8

### ISSUE THREAD

**Issue by tshawn** [macbre/phantomas#565]
I tried many times,but still cannot install the phantomas, it seems has some problem with Linux 2.6.32_1-15-0-0  node v0.12.2 npm  v2.14.8, here is the errors in last of the npm-debug.log,
please  help me.

make: *** [Release/obj.target/libsass/src/libsass/ast.o] err 1
make: live dir “/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32_1-15-0-0
gyp ERR! command "/home/users/xiaoguang01/.jumbo/bin/node" "/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32_1-15-0-0
npm ERR! argv "node" "/home/users/xiaoguang01/.jumbo/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/home/users/xiaoguang01/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/home/users/xiaoguang01/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/home/users/xiaoguang01/.jumbo/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "-g" "phantomas"
npm ERR! node v0.12.2
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/xiaoguang01/npm-debug.log

**Comment by tshawn** [comment]
In order to remove the interference factors, i tried npm replace cnpm,but still wrong :


make: *** [Release/obj.target/libsass/src/libsass/ast.o] err 1
make: live dir“/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32_1-15-0-0
gyp ERR! command "/home/users/xiaoguang01/.jumbo/bin/node" "/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32_1-15-0-0
npm ERR! argv "/home/users/xiaoguang01/.jumbo/bin/node" "/home/users/xiaoguang01/.jumbo/bin/npm" "install" "-g" "phantomas"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/xiaoguang01/npm-debug.log

**Comment by tshawn** [comment]
and in window 7 also has some promble : 

 npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phantomas"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0-alpha install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.0.0-alpha install script 'node install.js
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ct\zeus\npm-debug.log

**Comment by AdamTReineke** [comment]
+1 on Windows 10 with npm 2.5.1 and node 0.12.0.

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
```

**Comment by macbre** [comment]
This one is caused by a failing make of `node-sass` - @tshawn reported https://github.com/sass/node-sass/issues/1200 as well.

@AdamTReineke - your problem is a bit different (judging from your npm-debug.log):

```
41902 verbose unlock done using C:\Users\Adam\AppData\Roaming\npm-cache\_locks\analyze-css-8508104c78fd7454.lock for C:\phantomas\phantomas\node_modules\analyze-css
41903 verbose stack Error: phantomjs2@2.0.0-alpha install: `node install.js`
41903 verbose stack Exit status 1
41903 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
41903 verbose stack     at EventEmitter.emit (events.js:110:17)
41903 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
41903 verbose stack     at ChildProcess.emit (events.js:110:17)
41903 verbose stack     at maybeClose (child_process.js:1008:16)
41903 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

Can you try to `npm install macbre/phantomjs2-npm#version-2.0` - exit code 1 indicates that there's no PhantomJS 2 binary for your platform (but let's the full logs from it).
