### ISSUE TITLE
Real Network Timing Data via webkit2/PhantomJS 2.0

### ISSUE THREAD

**Issue by coryshaw** [macbre/phantomas#572]
It looks like with PhantomJS 2.0/webkit2, we now have access to Browser Network Timing data. Would be awesome to get this data into Phantomas:

https://gist.github.com/wesleyhales/b23f6d7dae5ef66ac630

**Comment by macbre** [comment]
DNS and TCP/IP connection times are reported since v1.13.0 - see #477

**Comment by coryshaw** [comment]
Ahh, nice! That's helpful for sure. That plus domComplete gives some well rounded metrics. Looking forward to tinkering with them. Thanks!

**Comment by macbre** [comment]
Cool, closing for now.
