### ISSUE TITLE
phantoms will not render page which the url contains hashmark

### ISSUE THREAD

**Issue by ynztyl10** [macbre/phantomas#576]
I'm testing a webpage by using phantomas,but I found the problem when I use the url contains hashmark such as 'http://bookstore2.shuqireader.com/route.php?sq_pg_param=bsbc&ver=151011#!/bid/3379630/'.
The screenshot of this page in Phantomas is all about blank,but it work perfectly by using PhantomJs alone.
I installed Phantomas by 'npm install'

Is it a bug?

**Comment by macbre** [comment]
Pages with the hashmark load just fine - http://example.com#foo for instance

In your case it's the timeout:

```
19:45:25.461 Timeout of 15 sec was reached!
19:45:25.463 Event timeout emitted
19:45:25.464 Timeout: gave up waiting for 1 HTTP response(s): <http://track.uc.cn:9080/collect?e_c=%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E6%89%93%E7%82%B9&e_a=page_event&e_n=0&pg=%E5%B0%81%E9%9D%A2%E9%A1%B5&appid=02124cda2b29&lt=event&uuid=924f7db75056b76a&cookie=1&res=1366x768&sn=0&ve=xxx&appver=xxx&placeid=xxx&softid=xxx&an1=newBookCover_data&ar1=success&at1=818>
```

phantomas hangs on the above request and eventually returns `phantomas: (252) Timeout`

**Comment by ynztyl10** [comment]
Well,some urls may only allow access to Chinese IP,so you found timeout there

In my case the hashmark is used to Route with url,just like backboneJS

    phantomas 'http://bookstore2.shuqireader.com/route.php?sq_pg_param=bsbc&ver=151011#!/bid/3379630/' --screenshot=image.png

I found `image.png` is all blank
