### ISSUE TITLE
Possibility to use in real browser (not PhantomJS)?

### ISSUE THREAD

**Issue by victor-homyakov** [macbre/phantomas#579]
I'd like to run phantomas modules in real browser, e.g. jQuery read after write detection, periodical DOM complexity checks etc.

In complex single page application there is little sense in making analysis of what will be loaded when you just open SPA (except of when you want to make SPA itself load faster). Many problems could be discovered only when you are interacting with SPA.

Is there any possibility to run checks in browser and output results in browser's console?

**Comment by macbre** [comment]
No. phantomas is a server-side tool only. There's no plan to add a support for running it in a "real" browser.

Please take a look at #474 where running phantomas against single page applications is discussed.
