### ISSUE TITLE
analyzeCss module doesn't work in node 4.2

### ISSUE THREAD

**Issue by ingoclaro** [macbre/phantomas#580]
I noticed that analyzeCss doesn't work well with node 4.2.
The subcommand returns err="" and a working results object, so it still goes into the error handling section.

**Comment by macbre** [comment]
@ingoclaro, can you provide the URL of the page that does not work for you?

**Comment by ingoclaro** [comment]
Sure!
steps to reproduce:

```
npm i phantomas
./node_modules/.bin/phantomas --scroll=false --analyze-css --screenshot page.png --modules analyzeCss https://www.groupon.com/getaways -v --debug

```
in node 0.10.33 -> * cssParsingErrors: 0
in node 4.2.2 -> * cssParsingErrors: 1
Offenders for cssParsingErrors (1):
 * <https://www.groupon.com/getaways-assets/assets/styles-3b99a08672.css>

If I run the css check script:

```
./node_modules/phantomas/node_modules/.bin/analyze-css --url https://www.groupon.com/getaways-assets/assets/styles-3b99a08672.css --json
```
I get a json output and "parsingErrors":0

**Comment by macbre** [comment]
@ingoclaro, I get the `parsingErrors: 0` as well (when executing `analyze-css` directly), but the JSON is not complete (that's why phantomas claims it's an error). For me it ends at:

```
".card-control .deal-status-overlay .stamp-wrapper .stamp 
```

**Comment by ingoclaro** [comment]
@macbre for me the json ends correctly:

executed:

```
./node_modules/phantomas/node_modules/.bin/analyze-css --url https://www.groupon.com/getaways-assets/assets/styles-3b99a08672.css --json
```

```
... ,"body.prom-night.getaways.seo .value-prop.icon-bucks:before (2 times)"]}}
```

I just tried it with the following versions:
node: v4.2.3
npm: 2.14.14
phantomas: 1.13.0
which internally uses analyze-css: 0.10.2

Still getting css parsing errors with phantomas itself.
