### ISSUE TITLE
CSV responses inconsistent

### ISSUE THREAD

**Issue by djenriquez** [macbre/phantomas#581]
Running `phantomas <URL> --modules requestsStats -R csv:no-header`, I will frequently get returned an inconsistent number of values:

Here is one response: `32,16,0,0,0,547754,948740,3980,1483,1494,1110,231008,21,1494,30,1483,67.5,65`

Here is another response:
`8,7,0,0,0,270163,272613,4084,1064,1078,6,1321,122540,23,3023,22,3023,50,49.5`

When adding headers, it appears the off value is the `6` between *1078* and *1321* in the second response. This field appears to be `smallestResponse`

Here are the headers:
`requests,gzipRequests,postRequests,httpsRequests,notFound,bodySize,contentLength,httpTrafficCompleted,timeToFirstByte,timeToLastByte,smallestResponse,biggestResponse,fastestResponse,slowestResponse,smallestLatency,biggestLatency,medianResponse,medianLatency`

Any ideas?

**Comment by djenriquez** [comment]
After some investigating with the tap reporter, the field that is added is `requestsWithTimeout`. This is problematic that the structure of the csv changes based on the behaviors of the page. This prevents us from using the CSV as a comma-delimited defined source of output.

Is it possible to keep the csv fields consistent throughout?

**Comment by macbre** [comment]
@djenriquez, thanks for the bug report and the investigation.

Fixed in #582
