### ISSUE TITLE
Analyze-Css module incorrect processing of query parameters

### ISSUE THREAD

**Issue by hmmdeif** [macbre/phantomas#587]
System: Windows

Example of a css file that will fail to be analyzed due to incorrect parsing: `http://www.example.com/css.css?p=1&p=2`.

Since & is a special character in cmd.exe, it will disregard `&p=2` and throw an error saying that it is an invalid command.

I solved this for myself by modifying `modules\analyzeCss.js:135` to `analyzeCss(['--url', entry.url.replace(/&/g, "^^^&")]);` which escapes the ampersands.

**Comment by macbre** [comment]
Fixed.

@hmmdeif, can you check if it works for you? I do not have access to any Windows machine.
