### ISSUE TITLE
CommonJS Module Options

### ISSUE THREAD

**Issue by arb** [macbre/phantomas#590]
What are the available options for using the npm module directly? I wasn't able to find this documented anywhere or an example.

**Comment by macbre** [comment]
For the start - https://github.com/macbre/phantomas/blob/devel/examples/promise.js

**Comment by EFF** [comment]
@arb I'm pretty sure options are all the same as the one you use in the CLI. You simply need to pass an option object as a second parameter in the phantomas function

example:
```
var phantomas = require('phantomas');

var options = {
	'assert-requests' : 10,
        'analyze-css': true,
	// engine: 'webkit2'
	//...
}

phantomas('https://snipcart.com', options, function(err, rawRes, results){
        if (err) console.log(err);
        else console.log(results.getMetrics());
});

```
