### ISSUE TITLE
Json output is invalid and truncated for large reports

### ISSUE THREAD

**Issue by amir-hadzic** [macbre/phantomas#596]
Hi!

I've noticed that phantomas doesn't output the complete json results for websites that produce large reports (long offenders list). The output is simply cut at some point, and the result is invalid json.

Here are the steps to reproduce the issue:

- Checkout master and run `npm install`
- Run `./bin/phantomas.js http://www.nytimes.com -R json`
- Note that the output is truncated

Seems like the issue is that `doneFn()`, and consequently `process.exit()` is called before the output is flushed. As a workaround, I'm executing `process.exit()` only if there's an error, otherwise the process ends with `0` anyways. Not sure if that's good enough for a pull request.

As a side note, if you redirect the output to a file (``./bin/phantomas.js http://www.nytimes.com -R json > out.json`), the output is complete. Not sure what's the difference.

**Comment by anlutro** [comment]
I can add that the JSON seems to be truncated at exactly 65275 characters, at which point a NULL character seems to be appended.

**Comment by macbre** [comment]
@amir-hadzic, can you provide the version of nodejs you're using to reproduce this issue?

JSON reporter works fine for me (nodejs v4.4.0):

```
$ ./bin/phantomas.js http://www.nytimes.com -R json | wc -c
52226
```

However (as @anlutro suggests) it may work because the JSON is shorter than 65275 characters.

**Comment by macbre** [comment]
> `process.stderr` and `process.stdout` are unlike other streams in Node.js in that they cannot be closed (`end()` will throw), they never emit the 'finish' event and that writes can block when output is redirected to a file (although disks are fast and operating systems normally employ write-back caching so it should be a very rare occurrence indeed.)

https://nodejs.org/api/process.html#process_process_stdout
