### ISSUE TITLE
cookie parameter is causing error

### ISSUE THREAD

**Issue by neighbordog** [macbre/phantomas#597]
I have been running into issues while using phantomas with the cookie parameter. 

Here's the error I'm getting:
> phantomas: (255) Failed to parse JSON with the results

[Link to full debug log](https://gist.github.com/neighbordog/df5f38f6b7a72ae8143d#file-phantomas-debug-log)

The bug seems to be caused by [extensions/cookies/cookies.js line 76](https://github.com/macbre/phantomas/blob/114379a2792cbe6dd2fde89fd0207f22b3a4b9a0/extensions/cookies/cookies.js#L76)

I switched:

```
if (!phantom.addCookie(cookie)) {
   throw 'PhantomJS could not add cookie: ' + JSON.stringify(cookie);
}
```

with a try statement like so:

```
try {
    phantom.addCookie(cookie);
} catch (ex) {
   debug('Error when parsing cookie (%s): "%s"', ex, JSON.stringify(cookie));

   // Return EXIT_ERROR
   if (code < 250) {
      code = 255;
   }
   errStream.push('phantomas: (' + code + ') PhantomJS could not add cookies. \n');
}
```

which seems to resolve the problem. I'm just not sure if this the right approach to fix this.

I'm using version 1.14.0 via npm and running on OS X.

**Comment by gmetais** [comment]
This bug is related to: https://github.com/ariya/phantomjs/issues/14047

**Comment by gmetais** [comment]
Hi @macbre!

Could we find a quick fix for this? The --cookie option is currently 100% broken.

As PhantomJS 2.1 never returns true to the `.addCookie()` function, it seems to me Phantomas could just "fire and forget" the call. At least until a new version of PhantomJS is out.
