### ISSUE TITLE
Cookie problem

### ISSUE THREAD

**Issue by urbanmichal** [macbre/phantomas#604]
Hi guys,

I've got problem with such execution:

phantomas http://michalu/shared/Start/Index --silent --reporter=csv:timestamp:url:no-header --modules=requests **--cookie='.ASPXAUTH=E83BA9755F0F4395C[...];domain=michalu**' >> PerformanceTests/2016-03-14-11-00-45.csv

**phantomas: (255) Failed to parse JSON with the results**

Cookie value is of course long:

'.ASPXAUTH=E83BA9755F0F4395CE9A780B11A0205189E87571D38A674437BBC7FF1C8EB061866D8172294085F6BE931E6B62A15838E0C006D84DE33CC00ABFBBFB6DFCEF7B922A2489CDF8ABE391EA539C0028BCCF1340A8B4BBA4191CB173BF502B8F6844322A821C8BF6B06542ACF210CFB36F5CB6806CB8144A8AF9583BD2DE60CFFF791D0D9B79D2CE43E698B87B2CEF949BA12CB3D3EFE9CFBE82BF13964BC5D4DC6B676570510CB4658EA60255C03C861047BEFA04E448E9873DDB5B7891B2FF6F182D80E59D67808DDCEE2E5922290859EEB35B3AA4ACACD452C6FD650B35930FD7E4A97B744FB1E74004E6F4D2F3713A1A291E9E4257361D76E5ECEBDD29BE7D85350C8CA1D65B90F038ACB0F3590DBB6F8EA32022F97DBC0A4F275924A41647DFBD60718E2A37E8E25E02FBB631980BDF60291BC1F86288F03C02B4CA7244BDC84452BF0983317A39B58B3DFFD9F527920E447F90710CB50C321E63DFEC5C248BE460B58D166D14123B3E5E6D4D7983382C52E4FEFE306D367E59E1152C39AE1B30A4C0C676156669983C28325E7F498CB795BEF6F945580316C241FC28DFA0AAD5B329AB79039D87E7AFF3084A86F73B770E11A40E1BD8823F55C6F639892F7E616C583F73E4863A05C3D7345975C973BB9D48BD3C27D4E23C8E7F66C17A18208D19EF64740CD537C14A48573CE001778BEF57DEA085E9013A05840CCD311C16A510EEF09765BD6AC1ABE9788ED1F46A1133E7D1B46EC0909DD67398856B4DC10EAE100381EFB95D77BDCEA3CDEB853824F5FAC16043BD08AEA478D0FD4B3E86A260774E3B171E20C4A5A1E32BDBA64D6D4B20B81DFB4C3FC44941A97E562D7D4FB8694B9AFBBEBDB8A14D166BF85CEC057388145E8F878888935EC08A6E3443D67DA1A6EBC86ACF73C4AA5735D12468EA9C067BBA0BFDB09F376EBCA922FCC36C6FAEF513E80C2F42ADBB4F978835C6AD0B659C22161E4353045BF766B9CA27453099F09AFD6602AA19AB68DFDC525A79D4E612E47F6238C49C68F3C11D892C77D376A2675554D40E7A03FAE4D358FDA4DFB191CEC55971FF336693D495C4948AA60C6F6F55CDE4A7009A16ED0DBD8062585A2806F5ADD9CCEA76F9C14C8EEA1947839C37B1795A1BA1D2F4FCEC3057183C9C1E8F654685A9D9F1109E891FF3B183BD1D9B899998E43B3D7404774C5D;domain=michalu'

**Comment by macbre** [comment]
Can you run phantomas with `--verbose` flag instead of `--silent` and provide the output here (via gist)?

**Comment by urbanmichal** [comment]
macbre, yes - https://gist.github.com/urbanmichal/512b4c795a654b658fe5

**Comment by gmetais** [comment]
Same as #597.

**Comment by macbre** [comment]
Fixed by #621
