### ISSUE TITLE
Init event triggered at the end of the page load

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#606]
I have a module that listens to the the `init` event, and I've got a bug that triggers the event a second time, at the very end of the run, after the "Done!" log trace.

When inspecting the `--verbose` logs, here is what I see with Phantomas v1.13 and v1.14:
```
11:29:52.523 Done!
11:29:52.524 Event exit emitted
11:29:52.525 onInit: was already triggered for <http://www.free.fr/freebox/>
11:29:52.526 phantomas scope injected
11:29:52.527 onInit: page object initialized
11:29:52.527 Event init emitted
```

With Phantomas v1.12, it looked like this:
```
11:35:56.894 Done!
11:35:56.894 Event exit emitted
11:35:56.902 onInit: was already triggered
11:35:56.903 onInit: was already triggered
```

The change that caused the problem is this one: https://github.com/macbre/phantomas/commit/2665dd125d6a25867f9ce8b178c06def8132bf09

The last time this `onInitialized` function is called, the page url is `about:blank`. Maybe the problem can be fixed by escaping the function when detecting `about:blank`. Would you like a pull request?

**Comment by macbre** [comment]
>  Would you like a pull request?

Yes, please :) And thanks for reporting the issue.
