### ISSUE TITLE
Incoherent metrics after a JavaScript redirection

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#611]
Hi :)

When the analyzed page makes a JS redirection, phantomas loads the new URL until it is complete (since https://github.com/macbre/phantomas/pull/557). The problem is that some metrics are counting for both pages (`requests` for example), while some others are only counting for the first page (`DOMqueries` for example). I think it should be fixed.

In the second case, this is because the DOMqueries module initializes itself with the `once` function:
```JS
phantomas.once('init', function() {
    ...
}
```

The `init` event triggers twice, but the `once` function prevents the module to initialize on the second page. The Phantomas scope is not entirely injected. I would replace the `.once()` by a `.on()`, in this module and in the other similar modules. But since I'm not sure why you wrote it like that, I'm afraid to do a pull-request!

**Comment by macbre** [comment]
AFAIR the reason for using `once` was the issue with `init` event being called more than once. As it's fixed, feel free to replace `once()` with `on()`.

**Comment by macbre** [comment]
Fixed by #612
