### ISSUE TITLE
Timeout caused by synchronous XMLHttpRequests

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#620]
As I wrote in my last pull-request (https://github.com/macbre/phantomas/pull/618), when a page sends a synchronous XMLHttpRequest, it is not counted in the requests and it makes phantomas timeout.

It seems to be related to this PhantomJS bug: https://github.com/ariya/phantomjs/issues/11284

**Comment by amol-** [comment]
I noticed you can usually work around those by using `--stop-at-load` option, depending on which metric you are looking at.

**Comment by macbre** [comment]
Let's see if headless Chromium handles these...
