### ISSUE TITLE
Move elasticsearch to an external npm module

### ISSUE THREAD

**Issue by macbre** [macbre/phantomas#625]
```
$ npm ls

├─┬ elasticsearch@10.1.3
│ ├─┬ chalk@1.1.1
│ │ ├─┬ ansi-styles@2.2.0
│ │ │ └── color-convert@1.0.0
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├── forever-agent@0.6.1
│ ├── lodash@3.10.1
│ ├── lodash-compat@3.10.2
│ └── promise-js@0.0.6
```

See #593

https://github.com/macbre/phantomas-reporter-elasticsearch / pinging @EFF / https://github.com/EFF/phantomas-reporter-cloudwatch

* [ ] Support reporters that handle node-style callbacks (`(err, resp) => {}`)

**Comment by macbre** [comment]
``
$ npm publish 
+ phantomas-reporter-elasticsearch@1.0.0
```

**Comment by EFF** [comment]
oh great ! thank you for this 👍

**Comment by macbre** [comment]
[v1.17.0](https://github.com/macbre/phantomas/releases/tag/v1.17.0) has been released :)
