### ISSUE TITLE
Question : Should we emit 'send' and 'recv' in ajax requests profiling

### ISSUE THREAD

**Issue by EFF** [macbre/phantomas#633]
Hey there, I think it could be cool to listen on ajax request send and ajax request received just like we do in the requestMonitor. I'd like to react in someway when an ajax request is sent or received which I think is not possible at the moment. I don't mind having a 'ajaxSend' and a 'ajaxRecv' events if it's necessary. What do you think?

**Comment by macbre** [comment]
@EFF, can you provide an example when AJAX requests do not trigger `send` and `recv` events? They should be handled like all the rest of HTTP requests, i.e. trigger PhantomJS events.

**Comment by EFF** [comment]
I thought since you moved the ajax request profiling in a dedicated script, they wouldn't be spyed in the requestMonitor. That was only my intuition but I haven't tried .. Sorry for the bothering then.
