### ISSUE TITLE
Ability to login and then run phantomas?

### ISSUE THREAD

**Issue by anandbagmar** [macbre/phantomas#635]
Hi,
I am trying to use phantomas to get the metrics for my site. This site requires to login first (login page), before being able to access any other pages. Is there a way to do that? (http-auth does not work for me). Thanks in advance!

**Comment by macbre** [comment]
The easiest option here is to use a simple script (Python, PHP, LanguageOfYourChoice) that will perform the login on your site and emit required cookies. These cookies can then be passed to phantomas via `cookie` option:

```
  --cookie                  document.cookie formatted string for setting a single cookie (e.g. "bar=foo;domain=url")       
```

Phantomas does not support (and probably never will) requesting several URLs during the same phantomas "session".
