### ISSUE TITLE
Duplicate request reported for CSS loaded via LoadCSS

### ISSUE THREAD

**Issue by luboskmetko** [macbre/phantomas#638]
When CSS is loaded via https://github.com/filamentgroup/loadCSS, it's reported as a duplicate request, please see https://github.com/gmetais/YellowLabTools/issues/156

**Comment by macbre** [comment]
Closing as @gmetais is unable to reproduce this issue (see https://github.com/gmetais/YellowLabTools/issues/156)

**Comment by gmetais** [comment]
Oops sorry, I forgot to tell you!
