### ISSUE TITLE
slimerjs install error

### ISSUE THREAD

**Issue by fabmygit** [macbre/phantomas#640]
I have been trying a couple of hours on amazon EC2 linux (amazon linux +
ubuntu) to install phanomas and I keep getting errors...

It seems, that the npm install routine fails during installation of
SlimerJS. I figured out, that this is probably not phantomas fault, because
even the normal "npm install slimerjs" fails. I guess that this is due to
the fact that the slimer download repository switched from http to https,
but thats only my guess...

CR https://github.com/macbre/phantomas/pull/639 would make slimerjs optional.

In the meantime, does anyone know of any workaround?

**Comment by macbre** [comment]
@fabmygit, can you provide more details (`npm install` output)?

It does work for me

```
macbre@bjornoya:/tmp$ npm install slimerjs

> slimerjs@0.906.1 install /tmp/node_modules/slimerjs
> node install.js

SlimerJS not found on PATH
Downloading https://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2
Saving to /tmp/slimerjs/slimerjs-0.9.6-linux-x86_64.tar.bz2
Receiving...
  [===========================-------------] 68%
Received 33587K total.
Extracting tar contents (via spawned process)
Removing /tmp/node_modules/slimerjs/lib/slimer
Copying extracted folder /tmp/slimerjs/slimerjs-0.9.6-linux-x86_64.tar.bz2-extract-1465725912333/slimerjs-0.9.6 -> /tmp/node_modules/slimerjs/lib/slimer
Writing location.js file
Done. SlimerJS binary available at /tmp/node_modules/slimerjs/lib/slimer/slimerjs

$ npm -v
n3.8.6
$ node -v
v5.11.1
```

**Comment by fabmygit** [comment]
on fresh ubuntu 14.04 ec2 machine:

> sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get autoremove && sudo apt-get autoclean
> 
> curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
> 
> sudo apt-get install -y nodejs
> 
> npm -v
> --> 3.8.6
> 
> 
> node -v
> --> v5.11.1
> 
> npm install slimerjs
> 
> > slimerjs@0.906.1 install /home/ubuntu/node_modules/slimerjs
> > node install.js
> 
> SlimerJS not found on PATH
> Downloading https://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2
> Saving to /tmp/slimerjs/slimerjs-0.9.6-linux-x86_64.tar.bz2
> Receiving...
> 
> Error requesting archive.
> Status: 403
> Request options: {
>   "uri": "https://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2",
>   "encoding": null,
>   "followRedirect": true,
>   "headers": {
>     "User-Agent": "npm/3.8.6 node/v5.11.1 linux x64"
>   },
>   "strictSSL": true
> }
> Response headers: {
>   "date": "Sun, 12 Jun 2016 15:19:02 GMT",
>   "server": "Apache/2.2.22 (Debian)",
>   "strict-transport-security": "max-age=15768000",
>   "vary": "Accept-Encoding",
>   "content-length": "252",
>   "connection": "close",
>   "content-type": "text/html; charset=iso-8859-1"
> }
> Make sure your network and proxy settings are correct.
> 
> If you continue to have issues, please report this full log at https://github.com/graingert/slimerjs
> npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
> npm WARN ubuntu No description
> npm WARN ubuntu No repository field.
> npm WARN ubuntu No README data
> npm WARN ubuntu No license field.
> npm ERR! Linux 3.13.0-74-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "slimerjs"
> npm ERR! node v5.11.1
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> 
> npm ERR! slimerjs@0.906.1 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the slimerjs@0.906.1 install script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the slimerjs package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs slimerjs
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls slimerjs
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/npm-debug.log
> 

Any ideas?

**Comment by macbre** [comment]
As npm suggests - "Make sure your network and proxy settings are correct.". Does fetching of tar.bz2 work via curl or wget?

**Comment by fabmygit** [comment]
No wget does not work. I checked ec2 instance security policies, still everything looks ok - no restrictions.

As all other updates e.g. from ubuntu sites work fine, my guess is that slimer.org blocks IPs from amazon cloud...

**Comment by fabmygit** [comment]
It's not just me...

https://github.com/graingert/slimerjs/issues/39

**Comment by fabmygit** [comment]
https://mobile.twitter.com/slimerjs/status/740123826969837568?lang=en

**Comment by graingert** [comment]
@macbre you should not depend on slimerjs in this project.

create engines like phantomas-engine-slimerjs phantomas-engine-phantomjs, then when someone sets:

```json
{
    "engine": "xyz"
}
```

do
```js
var engine = require('phantomas-engine-xyz').engine
```

Like babel etc.

Or even better support only:

```js
{
    "engine": require('phantomas-engine-slimerjs').engine
}
```

**Comment by macbre** [comment]
Reported as graingert/slimerjs#39 in slimerjs repo, closing for now.

**Comment by macbre** [comment]
@graingert, I totally agree - please take a look at #639

**Comment by graingert** [comment]
@macbre optionalDependencies still download. You should use a plugin style approach

**Comment by danielbeardsley** [comment]
This needs to be solved by phantomas and shouldn't wait for slimer-js. Meanwhile, anyone who tries to install phantomas on an AWS machine can't very easily and the failure is pretty mysterious. It took me a while to find this issue. Simply making a way to optionally install this optional dependency that apparently has never fully worked would be a good start.
