### ISSUE TITLE
Update phone and tablet user agents

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#642]
Hi Maciej!

The user agents in use for `--phone` and  `--tablet` options are quite old and some websites start to complain about it.

For example this is a Phantomas screenshot on http://www.nasa.gov/ :

![image](https://cloud.githubusercontent.com/assets/498031/16098657/86c1ac46-3354-11e6-8ead-033651b8f664.png)

The user-agents in use are: 
iPhone --> iOS 3
iPad --> iOS 4

The question is: Should Phantomas use the latest iOS version number so that no website complains? Or should it use an old iOS user-agent that's closer to the real capacities of PhantomJS 2.x but have some websites mark it as an old browser?

**Comment by macbre** [comment]
Let's use more up to date user agents (any suggestions here?) to avoid sites using user-agent based detection showing warning screens like the above. Sites using supported features detection will still be fine.

**Comment by gmetais** [comment]
Ok let's say iOS9 then:

**iPhone:** Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A452 Safari/601.1

**iPad:** Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B5110e Safari/601.1
