### ISSUE TITLE
Check CSS and JS loading order

### ISSUE THREAD

**Issue by macbre** [macbre/phantomas#647]
From Google Chrome "Web Page Performance" audits:
- The following external CSS files were included after an external JavaScript file in the document head. To ensure CSS files are downloaded in parallel, always include external CSS before external JavaScript.
- 1 inline script block was found in the head between an external CSS file and another resource. To allow parallel downloading, move the inline script before the external CSS file, or after the next resource.

See #487 for critical path handling

Suggested order in `<head>` tag:
1. inline JS
2. external CSS
3. external JS

**Comment by gmetais** [comment]
Hi @macbre,

I think these parallel download issues do not longer exist in modern browsers:
http://stackoverflow.com/questions/9271276/is-the-recommendation-to-include-css-before-javascript-invalid#answer-9272629

Browsers have 2 parsers, a fast parsed that reads the entire DOM, looking for external scripts/stylesheets/images to load, and a DOM parser that actually reads the HTML and renders or executes.

For me, the main issue is non-async third party content in the critical path.
