### ISSUE TITLE
jsErrors found but the page doesn't contain any error

### ISSUE THREAD

**Issue by AdriwanKenoby** [macbre/phantomas#654]
When I test this url : [http://www.pacificpeche.com](http://www.pacificpeche.com), i found a lot of jsErrors, however this page do not contain any errors...

Maybe related to #230  

jsErrors : 41

Offenders for jsErrors (41):
Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn: @ 8 / unknown fn: phantomjs://code/scope.js @ 216

Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / incrMetric(): phantomjs://code/scope.js @ 150 / unknown fn: @ 8 / unknown fn: phantomjs://code/scope.js @ 216 / $(): https://www.pacificpeche.com/js/prototype/prototype.js @ 2056 / initialize(): https://www.pacificpeche.com/js/varien/js.js @ 308 / initialize(): https://www.pacificpeche.com/js/soon/ajaxsearch/ajaxsearch.js @ 13 / klass(): https://www.pacificpeche.com/js/prototype/prototype.js @ 80

[...]

Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / spyEnabled(): phantomjs://code/scope.js @ 197 / unknown fn: @ 6 / unknown fn: @ 65 / unknown fn: @ 66
Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / spyEnabled(): phantomjs://code/scope.js @ 197 / unknown fn: @ 13 / unknown fn: @ 56 / unknown fn: @ 57
Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / spyEnabled(): phantomjs://code/scope.js @ 197 / unknown fn: @ 3 / unknown fn: @ 59 / unknown fn: @ 60
Error: phantomas: calling native console.log() failed ("TypeError: Type error")! - sendMsg(): phantomjs://code/scope.js @ 133 / log(): phantomjs://code/scope.js @ 138 / unknown fn: @ 14 / unknown fn: @ 16 / unknown fn: @ 17

**Comment by macbre** [comment]
This site customizes `console.log` which is used heavily by phantomas for PhantomJS - Node.js layers communication.

```js
console.log
(){
          logArray.logs.push(arguments)
          isDebug && origConsole.log && origConsole.log.apply(origConsole,arguments);
        }
```
