### ISSUE TITLE
Number of requests not correct (comparing with browser)

### ISSUE THREAD

**Issue by linediconsine** [macbre/phantomas#656]
HI All, and thanks for the amazing work on phantomas

Maybe I am wrong but I expect this

  "metrics": {
            "requests": 9,

**metrics.requests** to be the total number of requests done from this pages until document ready.
Is this correct?

If yes I am sorry that in my test (comparing with chrome)  this value seem not correct.

example:
http://phantomjs.org/  chrome 14 requests
http://phantomjs.org/  phantomas 9 requests

phantomas v1.15.1

Thanks for any help/feedback

**Comment by linediconsine** [comment]
Update to phantomas v1.16.0, I still see different results tested also with firefox

**Comment by macbre** [comment]
@linediconsine - thanks, please re-open if this issue is still valid after your tests.
