### ISSUE TITLE
How do I test an URL which requires post parameter in command line?

### ISSUE THREAD

**Issue by usherfu** [macbre/phantomas#657]
Hi,
I have been evaluating phantomas to our CI workflow. Basically we use phantomas to run test via jenkins upon each commit.

For a url such as https://example.com following command works great
phantomas https://example.com --format csv

However, if  it is  a page with post request, e.g. login data,  such as https://example.com/login, how can I provide those parameters via command line?

Thanks for any tips!

**Comment by macbre** [comment]
Currently phantomas does not support making a POST request (with data passed). It can be implemented as [PhantomJS has support for POST requests](http://phantomjs.org/api/webpage/method/open.html).

Please note that phantomas can only be used to measure the performance of a single request. Logging via form and then checking a page for logged-in user is not possible right now. You can consider wrapping a call to phantomas with a curl request to login form, getting a session cookie and then passing it to phantomas (via `--cookie`).

**Comment by usherfu** [comment]
Hi Macbre,
Do you have an example of how to calling the PhantomJS open method by phantomas? 

Thanks!

**Comment by macbre** [comment]
@usherfu  - correct, currently phantomas can only measure performance of a single webpage load.

> Additionally do you have an example of how to calling the PhantomJS open method by phantomas?

I don't quite understand your question.

**Comment by usherfu** [comment]
@macbre 
Thanks for the update and additional information.  #649 is exactly what I'd hoped for, testing multiple steps with one phantomas instance.  One related question, does it mean phantomas will support kinda of "scripting capability"? like [webpagetest](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting) 

Regarding my previous question of calling PhantomJS "open" method:  as you kindly suggested to look into [PhantomJS "open" ](http://phantomjs.org/api/webpage/method/open.html), however I am not sure how to call this method while running test with phantomas, any hint would help!  Thanks again!

**Comment by macbre** [comment]
Scripting capability would be a great feature! Let's start with #649 and support providing a sequence of URLs that phantomas should load and generate metrics for the set.

As for the PhantomJS open function. The link was just for a reference. In order to make a POST requests you'd need to modify phantomas source code (which you're welcome to :) ).

It's possible to run PhantomJS in a "Selenium" mode (via webdriver interface). However this API is limited and does not provide any insights into requests made by the browser.
