### ISSUE TITLE
Run fails when phantomas is an npm 3 dependency

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#664]
Npm 3 introduced a new "flatten" way to store packages in `node_modules`.

When running phantomas as a npm dependency, with the `--analyze-css` option, it executes this command: 
```
/my-project/node_modules/phantomas/node_modules/.bin/analyze-css --url http://www.somedomain.com/something.css --json
```
It results in a `No such file or directory` error.

This is a problem with npm 3, where the command should be:
```
/my-project/node_modules/.bin/analyze-css --url http://www.somedomain.com/something.css --json
```

I was able to temporarily fix this by replacing `node_modules/.bin/` by `../../node_modules/.bin/` here: https://github.com/macbre/phantomas/blob/devel/modules/analyzeCss/analyzeCss.js#L98

Not sure how to fix it so that it works with both npm 2 and 3. Do you have an idea?

**Comment by macbre** [comment]
Rough idea: let's determine the path to `analyze-css` dependency on Node.js level and pass it to PhantomJS-level script.

**Comment by macbre** [comment]
Use [`__dirname`](https://nodejs.org/api/modules.html#modules_the_module_wrapper) to get the absolute path to `analyze-css` module.

**Comment by macbre** [comment]
```js
> require('analyze-css')
{ [Function: analyzer]
  version: '0.12.3',
  path: '/home/macbre/github/phantomas/node_modules/analyze-css',
  pathBin: '/home/macbre/github/phantomas/node_modules/analyze-css/bin/analyze-css.js',
  EXIT_NEED_OPTIONS: 2,
  EXIT_PARSING_FAILED: 251,
  EXIT_EMPTY_CSS: 252,
  EXIT_CSS_PASSED_IS_NOT_STRING: 253,
  EXIT_URL_LOADING_FAILED: 254,
  EXIT_FILE_LOADING_FAILED: 255 }
```
