### ISSUE TITLE
support for multiple cookies

### ISSUE THREAD

**Issue by bobstrecansky** [macbre/phantomas#667]
It seems as if the support for multiple cookies is only available via a config.json:
https://github.com/macbre/phantomas/blob/devel/extensions/cookies/cookies.js#L22

Is there a way that we could get multiple cookies passed in via the command line?  It looks as if it could be passed into the cookiedParam var, but i'm not exactly sure how we would do this.

**Comment by eplle** [comment]
I hope that the enhancement in v1.18 will not only affect multiple cookies via the command line but also in node?

**Comment by macbre** [comment]
Let's implement it as follows:

> `--cookie='bar=foo;domain=url'` document.cookie formatted string for setting a single cookie

Handle pipe-separated cookies: `--cookie='bar=foo;domain=url|test=cookie'`
