### ISSUE TITLE
Latency for all assets

### ISSUE THREAD

**Issue by Lorenzo-Giacosa** [macbre/phantomas#668]
Is there a way to print **Latency** for all asset?

For example: 
`"imageCount": [
      "http:\/\/www.example.com\/img\/logo.png (6.38 kB) (LATENCY ms)"]`

**Comment by macbre** [comment]
I assume that by latency you mean time to the first byte of the response (as introduced in #134 - `smallestLatency` metric and similar ones).

What if TTFB (time to first byte aka latency) would be added to the `*Count` offenders for each type of assets fetched? Let's say something like the following:

```
Offenders for cssCount (3):
 * https://assets-cdn.github.com/assets/site-4a18dc1c93cc7113ea22c7c6b62826f621b52a57f32caea97c682100ac10de36.css (size: 13.12 kB, latency: 206 ms)
 * https://assets-cdn.github.com/assets/frameworks-c07ca57e8924150abac5f078c979cff71dc056c6015560c7bf45898e963137e4.css (size: 6.25 kB, latency: 345 ms)
 * https://assets-cdn.github.com/assets/github-2d1b79a5296eab9613c29bbac983651835f5ea62fb87eb9b860b7240dd28d934.css (size: 6.39 kB, latency: 410 ms)
```

**Comment by macbre** [comment]
An example:

```
Offenders for htmlCount (1):
 * http://192.168.1.100:8888/lazy-loadable-images.html (0.77 kB, latency: 9 ms)

Offenders for imageCount (3):
 * http://192.168.1.100:8888/static/mdn.png (22.46 kB, latency: 6 ms)
 * http://192.168.1.100:8888/static/example.svg (0.45 kB, latency: 8 ms)
 * http://192.168.1.100:8888/static/blank.gif (0.04 kB, latency: 41 ms)
```

**Comment by Lorenzo-Giacosa** [comment]
Great job! Thanks.

*Lorenzo Giacosa*

✆ +39 339 36 13 409
✉ lorenzo.giacosa@axant.it

2016-12-23 18:37 GMT+01:00 Maciej Brencz <notifications@github.com>:
