### ISSUE TITLE
How do I get the output of calls to console.log in phantomas?

### ISSUE THREAD

**Issue by oldtinroof** [macbre/phantomas#669]
This was originally [asked on SO](http://stackoverflow.com/questions/40214429/how-do-i-get-the-output-of-calls-to-console-log-in-phantomas), but wanted to try and see if there was an answer on here (with some minor edits):

I'm using Phantomas on a single page app (Angular 1.57) that we're working on, and there seems to be some point that it stops loading the page - there's a redirect after our SSO auth is complete (which does generate a cookie), but it doesn't go any further.

It's working fine in PhantomJS on it's own (I've done screenshots with both to test), but to debug properly I'd like to see the content that is pushed to console.log by our app.

Is there anyway to get that output either to the terminal or a file? I've got verbose, debug and log options turned on, but I know our app sends a lot of stuff to console.log and it's not appearing anywhere - and it would definitely log an error to the console if it failed to get the cookie from the SSO.

Any help is much appreciated :)

**Comment by macbre** [comment]
@oldtinroof, all calls to `console.log` are intercepted by phantomas (they're used for IPC between PhantomJS and Node.js layer) and logged to stderr:

```
$ ./bin/phantomas.js --verbose http://127.0.0.1:8888/jquery-ajax.html 2>&1 | grep "console.log"
12:50:15.566 console.log: $.get
12:50:15.573 console.log: XMLHttpRequest
12:50:15.582 console.log: Ajax: done

$ ack-grep console test/webroot/jquery-ajax.html 
		console.log('$.get');
			console.log('Ajax: done');
		console.log('XMLHttpRequest');
```

**Comment by oldtinroof** [comment]
Ah that's strange, I'll dig deeper then and try to find out why it's not outputting what I'd expected.  Cheers for the headsup on a way to filter to just the console results.
