### ISSUE TITLE
Unable to set Config parameter

### ISSUE THREAD

**Issue by eplle** [macbre/phantomas#675]
Hi!

I´m unable to set the config parameter using phantomas npm module. Perhaps I only need an example of how to pass it to phantomas.

This is how i´m currently trying to pass it:

```
run = phantomas('url', {
	'config': 'config.json'
});
```

And the config.json looks something like this:
```
{
   "reporter": "json:pretty",
   "ignore-ssl-errors": true,
   "screenshot": true,
   "verbose": true,
   "cookies": [
      {
         "name": "GESESSION",
         "value": "......",
         "domain": "......"
      },
      {
         "name": "JSESSIONID",
         "value": ".....",
         "domain": "....."
      }
   ]
}
```

What im I doing wrong? :)

**Comment by macbre** [comment]
Providing config.json is only supported by command line tool. If you want to pass config when running as npm module simply pass the object when creating `phantomas` instance.

An example: https://github.com/macbre/phantomas/blob/devel/examples/promise.js
