### ISSUE TITLE
Handle environment variables in YAML config files

### ISSUE THREAD

**Issue by rbayliss** [macbre/phantomas#685]
It would be a really great feature to have the base URL be separate from the URL of the test.  The main use case for this is in having a single config file that you want to run on multiple environments of a site.  In my config file, I'd like to be able to say:
```yaml
url: /my-page
```

Then on the command line, be able to set the base with something like:
```bash
phantomas --config=my-config.yaml --base-url=http://foo.com
```
Is this implemented, or possible?  I'm happy to help out with a PR here, but I'm not sure where to start.

**Comment by macbre** [comment]
@rbayliss, great suggestion :+1: 

Personally, I like the way [Docker handles environment variables in their config files](https://docs.docker.com/compose/environment-variables/) (YAML as well). What if we use the same approach in Phantomas YAML config files? This will be even more flexible then additional `--base-url` option.

**Comment by rbayliss** [comment]
Yeah, even better!

**Comment by rbayliss** [comment]
Ah, just realized if this was supported for various configuration keys in the config file, it would also provide a way to change the report type on the fly too.  Sweetness!

**Comment by macbre** [comment]
Let's add the env variables handling in [optimist-config-file.js](https://github.com/macbre/phantomas/blob/devel/lib/optimist-config-file.js#L36) + consider moving it to a separate npm module (with tests).

**Comment by macbre** [comment]
````
$ npm publish 
+ optimist-config-file@1.0.0
```

https://www.npmjs.com/package/optimist-config-file
