### ISSUE TITLE
documented events does not fire

### ISSUE THREAD

**Issue by labeh** [macbre/phantomas#689]
The documented Events on https://github.com/macbre/phantomas/wiki/Events are not fired. I tried the Events "pageBeforeOpen", "pageOpen", "init" and also some of the generic Events from https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#wiki-webpage-onInitialized

Do you have a Suggestion for a workaround how to inject Cookies and some JS-Code for checking if a login was successfull?

**Comment by macbre** [comment]
I've updated https://github.com/macbre/phantomas/wiki/Events to describe the distinction between internal phantomas events (fired by phantomas wrapper on PhantomJS and used by phantomas modules) and phantomas events that propagates (via ipc) to phantomas npm module (and can be used by Node.js code using phantomas npm module).

Cookies can be injected via `cookie` option - https://github.com/macbre/phantomas/issues/667#issuecomment-269000934

Hope that helps.
