### ISSUE TITLE
Add file url in offenders for cssDuplicatedSelectors 

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#693]
Hi @macbre !

Having the file name added to offenders in cssDuplicatedSelectors rule would be great:

Currently: 
```
#header.row (2 times)
```

After:
```
#header.row (2 times) <http://www.domain.com/css/navigation.min.css>
```

Having the lines and rows of the rules would be interesting too, but it looks difficult to achieve from what I see.

----

Originally reported by @a701440 / https://github.com/gmetais/YellowLabTools/issues/230

**Comment by macbre** [comment]
An example:

```
Offenders for cssDuplicatedSelectors (1):
 * p (2 times) [inline CSS]
```
