### ISSUE TITLE
Tryin phantomjs 2.5 in a lambda function

### ISSUE THREAD

**Issue by moelheni** [macbre/phantomas#703]
I am using a lambda function to launch a process of phantomjs (the binary is inside the pacakge).
This method worked fine with phantomjs 2.1.1 but when using the binary for the version 2.5.1 I got this error:

    ./phantomjs: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

**Comment by macbre** [comment]
@insatmc, please take a look at #702. PhantomJS 2.5 is still in pretty early stage.
