### ISSUE TITLE
Require public-ip for custom module always fail - cannot find module 'dgram'

### ISSUE THREAD

**Issue by AdriwanKenoby** [macbre/phantomas#715]
Hi @macbre ,

I try to add the public ip of the host which run phantomas to the set of metrics.

So I had written this piece of code, put in in modules/reportFrom/reportFrom.js, I need some help please to get it work.
```
'use strict';

exports.version = '0.1';

const publicIp = require('public-ip');

exports.module = function (phantomas) {

    publicIp.v4().then(function (ip) {
        phantomas.setMetric('reportFrom', ip, true); // @desc ip of the host which exec phantomas
    });
};

```
public-ip package needs dgram which is built-in with Nodejs so why I have this error : 
Error: Cannot find module 'dgram' ?

**Comment by AdriwanKenoby** [comment]
I have tried another approach but still not working:

```
'use strict';

exports.version = '0.1';

var publicIp = require('public-ip');

exports.module = function (phantomas) {

    phantomas.setMetricEvaluate('reportFrom', function () {
        publicIp.v4().then(function (ip) {
            return ip;
        });
    });
};
```
Error: Cannot find module 'dgram'

**Comment by AdriwanKenoby** [comment]
As I record metrics from different hosts, I would like to register the public-ip come from the report in order to prevent false-positive. I don't understand why the directive require('public-ip') always fails in this context. I have used it in another project and it works perfectly.

Maybe their is some context rely to phantomjs that i don't understand, help would be really appreciate.

Thanks.

**Comment by macbre** [comment]
Closing as per https://github.com/sindresorhus/public-ip/issues/21.

phantomas v2.0.0 is almost there.
