### ISSUE TITLE
it doesn't support Centos 7? error libjpeg8

### ISSUE THREAD

**Issue by lemonl2** [macbre/phantomas#745]
➜  ~ ldd /usr/lib/node_modules/phantomas/node_modules/phantomjs-prebuilt-macbre/lib/phantom/bin/phantomjs
	linux-vdso.so.1 =>  (0x00007ffccdda8000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f83f7363000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f83f70a4000)
	libjpeg.so.8 => not found
	libssl.so.1.0.0 => not found
	libz.so.1 => /lib64/libz.so.1 (0x00007f83f6e8e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f83f6c8a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f83f6a82000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f83f6866000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f83f6640000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f83f633e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f83f5f71000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f83fd15a000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f83f5d47000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f83f5b42000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f83f5932000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f83f5707000)

**Comment by lemonl2** [comment]
➜  ~ phantomas https://github.com/macbre/phantomas --verbose
Debug: /usr/lib/node_modules/phantomas/node_modules/phantomjs-prebuilt-macbre/lib/phantom/bin/phantomjs: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

**Comment by lemonl2** [comment]
I've already installed  libjpeg-turbo.x86_64 0:1.2.90-6.el7 and  libjpeg-turbo-devel.x86_64 0:1.2.90-6.el7

**Comment by macbre** [comment]
phantomas v2.0.0 will solve this issue.
