### ISSUE TITLE
The neverending test

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#846]
Hi @macbre,

I'm currently running live a beta version of Yellow Lab Tools that uses Phantomas v2. Globally most of the pages run perfectly well 🎉. But there are a few urls (maybe one on 40) that freeze Phantomas (and YLT).

Here is one of them: https://www.premium-sales.com/

**Steps to reproduce:**
Run Phantomas as a node module with the following code:
```js
const phantomas = require("./lib/index");

const promise = phantomas(
  "https://www.premium-sales.com/",
  {
    "timeout": 60,
    "screenshot": "tmp/temp-screenshot.png"
  }
);

promise
  .then((results) => {
    console.log("Metrics", results.getMetrics());
  })
  .catch((res) => {
    console.error(res);
    console.log("Error code #%d", res.code);
    process.exit(res.code);
  });
```

**Result:**
Phantomas get stuck in a loop that keeps logging some DOM mutations related to what seems to be related to a JS animation. The browser does not throw network requests anymore, so this is not related to the `networkIdle0` option.

It rather seems to be related to screenshots. If you comment the screenshot option, Phantomas completes correctly.

Note: this problem does not happen on the CLI version of Phantomas, just the node module.

**Comment by macbre** [comment]
@gmetais - thanks for giving phantomas a try on production and reporting this issue.

Will take a look into when working on v2.2

**Comment by gmetais** [comment]
I've made a mistake in my initial bug report. The above test was blocked in an infinite loop because of the `tmp` folder from `"screenshot": "tmp/temp-screenshot.png"` option. The directory did not exist.

The bug I wanted to report is not related to screenshots, but to analyze-css. It can be reproduced like that:

```js
const phantomas = require("./lib/index");

const promise = phantomas(
  "https://www.premium-sales.com/",
  {
    "phone": true,
    "analyze-css": true
  }
);

promise
  .then((results) => {
    console.log("Metrics", results.getMetrics());
  })
  .catch((res) => {
    console.error(res);
    console.log("Error code #%d", res.code);
    process.exit(res.code);
  });
```

But it does work when I remove the analyze-css option.

Same as in my initial bug report, it does not happen when I run the same test on CLI: `DEBUG=* node bin/phantomas.js --url https://www.premium-sales.com/ --analyze-css --phone`


The good news is I've managed to fix it!

The issue was in the log:

```

(node:4098) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No resource with given identifier found
    at /Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Object.<anonymous> (/Users/gaelmetais/Documents/GitHub/phantomas/lib/browser.js:191:35)
    at /Users/gaelmetais/Documents/GitHub/phantomas/modules/analyzeCss/analyzeCss.js:207:31
    at new Promise (<anonymous>)
    at /Users/gaelmetais/Documents/GitHub/phantomas/modules/analyzeCss/analyzeCss.js:202:9
    at Array.forEach (<anonymous>)
    at /Users/gaelmetais/Documents/GitHub/phantomas/modules/analyzeCss/analyzeCss.js:200:17
    at /Users/gaelmetais/Documents/GitHub/phantomas/lib/AwaitEventEmitter.js:15:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4098) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4098) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

"Unhandled promise" means there is a missing try-catch around the code used by analyze-css.
Here precisely: https://github.com/macbre/phantomas/blob/v2.1.0/lib/browser.js#L191
I'm going to create a pull request.


Actually, the other bug with screenshots was also triggering an unhandled promise, I'll try to fix it as well. And I think I've spotted another one.

**Comment by gmetais** [comment]
By the way,

From what I've understood, the bug is caused because Network.getResponseBody (https://chromedevtools.github.io/devtools-protocol/tot/Network#method-getResponseBody) is not always reliable.

For example, the browser started to download some CSS files, then a JS redirection happens. On page change, the browser clears its file buffer. As a result, calling Network.getResponseBody on CSS files from the previous page fails.

**Comment by macbre** [comment]
Nice investigation :slightly_smiling_face: Thanks!
