### ISSUE TITLE
Issues with full page screenshots

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#853]
I have noticed several issues that are related to screenshots, and they seem to be related to how Puppeteer handles **full page** screenshots.

It looks like Puppeteer resizes the browser's viewport so that it covers the page dimensions, just before taking the screenshot. For example, if we set a viewport of 1200x800 in Phantomas but the full page size is 1200x9999, then Puppeteer will resize the viewport to 120x9999. See [here in the code](https://github.com/puppeteer/puppeteer/blob/5ea76e9333c42ab5a751ca01aa5676a662f6c063/src/common/Page.ts#L1690) and [here in an issue](https://github.com/puppeteer/puppeteer/issues/3371).

The first issue is that full page screenshots don't always represent what real users see on their browsers. Typically, if some elements on the page are positioned or sized relatively to the screen's height, such as a centered popin, then they will move or be resized.

I've been launching some tests with Puppeteer's full page option enabled, then disabled:

![phantomas-screenshots](https://user-images.githubusercontent.com/498031/105407148-195fbe00-5c0c-11eb-98f6-cc2113cde173.jpg)

The second issue is that image lazyloading will be triggered for images under the fold. Now I have a better understanding of [this issue](https://github.com/macbre/phantomas/issues/828) I've raised a few weeks ago. The browser is resized, so both native lazyloading and JS lazyloading libraries will think that all images on the page need to be loaded. This makes the "lazyloadableImages" metric unreliable.

The third issue is when a page is very, very long, taking a full page screenshot can crash Puppeteer, especially if the hosting machine has insufficient memory.

I can do a pull request, but I'm wondering about the solution. For my use case, I would like to be able to switch Phantomas screenshots to non-fullpage. Should we impose that or should we add an option? And if it becomes an option, what should be the default value?

**Comment by macbre** [comment]
I vote for a screenshot for the viewport, with an option to take the entire page screenshot.

Thanks for investigating this issue!

**Comment by macbre** [comment]
Fixed by #854
