### ISSUE TITLE
Chrome flags required in an Amazon Lambda Docker image

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#914]
I'm almost done making Phantomas run in an AWS Lambda Docker image. But I have an issue with Chrome not launching at all. I found a few answers thanks to this project: https://github.com/alixaxel/chrome-aws-lambda

It looks like Chrome requires to be started with the following additional flags: `--no-sandbox --no-zygote --disable-gpu --single-process`.

I think this use case won't be shared with many other Phantomas users and I don't want to complexify Phantomas with some hard to understand options such as `--no-sandbox` or `--no-zygote`. Any idea how we could do that? Would a single `--aws-lambda-compatibility` option be understandable/useful?

I still have the option to modify Phantomas' code inside my Docker image.

**Comment by macbre** [comment]
Does AWS Lambda set any specific environment variable that we can detect and act accordingly (e.g. pass appropriate set of options to puppeteer when launching Chromium)?

**Comment by macbre** [comment]
@gmetais - I assume you're trying to use ["Container image" Lambda function](https://docs.aws.amazon.com/lambda/latest/dg/configuration-images.html?icmpid=docs_lambda_help)?

https://docs.aws.amazon.com/lambda/latest/dg/configuration-images.html#configuration-images-settings - an env variable can be set then - `PHANTOMAS_AS_LAMBDA`?

**Comment by gmetais** [comment]
Good idea!

Yes we can look at `process.env.LAMBDA_TASK_ROOT`. It is supposed to contain the directory name, so if the variable is a string, we can assume we're in a Lambda.

**Comment by gmetais** [comment]
Otherwise yes, I can add a specific variable on my environment.

**Comment by macbre** [comment]
```
process.env.LAMBDA_TASK_ROOT
```

Is this env variable set by the Amazon's Lambda stack for all lambdas? If so, let's use it - people can then use Phantomas server-lessly 😉  way easier - no need to set this yet another env variable that you need to remember about.

@gmetais , can you prepare a pull request then?

I'm wondering if we can automatically test phantomas in lambda somehow.

**Comment by macbre** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime - it is set 🙂 So, let's use it.

**Comment by gmetais** [comment]
> I'm wondering if we can automatically test phantomas in lambda somehow.

It is possible, but it's kind of annoying. We first need to provide one of those:

- a zip file that includes the entire project, including dependencies compiled for Lambda machines
- a built docker image running on "Amazon Linux"

Then send it to AWS for deployment. And wait for deployment before testing.

**Comment by macbre** [comment]
True, it's quite a complex procedure. Maybe as a nightly cron job? Let's consider it outside this thread.
